/**
 * ENTITATS DE DENUNCIEM.CAT
 * ────────────────────────
 * Cada entitat és una fitxa estàndard amb els mateixos camps.
 *
 * Camps:
 *   id                slug únic (per enllaç directe)
 *   nom               nom complet
 *   tipus             'administratiu' | 'legal' | 'estrategic' | 'social' | 'sectorial'
 *   ambit             categoria temàtica (lliure, curta)
 *   descripcio_breu   1 línia — es mostra a la targeta del grid
 *   per_a_que         1-2 frases — què aconsegueix l'usuari
 *   quan_usar         array d'ítems — casos concrets
 *   que_esperar       array d'ítems — què passarà després
 *   punts_forts       array d'ítems
 *   limitacions       array d'ítems
 *   resultat_habitual 1 frase
 *   temps             orientatiu ('Dies', 'Setmanes', 'Setmanes / mesos', 'Mesos', 'Mesos / anys')
 *   enllac            URL directe al formulari / canal / contacte
 *   pos               [col_rel, row_rel] de 0 a 1 — posició al grid d'escriptori (10×6)
 *   pos_mobil         [col_rel, row_rel] de 0 a 1 — posició al grid mòbil (6×10)
 *
 * Per afegir-ne: copia un bloc, canvia els camps i comprova que l'id sigui únic.
 */

const TIPUS_META = {
  administratiu: { nom: 'Administratiu',       color: '#2563EB', descripcio: 'Canals oficials que supervisen o resolen davant l\'administració i empreses.' },
  legal:         { nom: 'Legal',               color: '#B91C1C', descripcio: 'Via penal, sancionadora o d\'investigació oficial.' },
  estrategic:    { nom: 'Legal estratègic',    color: '#7C2D12', descripcio: 'Accions judicials amb voluntat d\'impacte i precedent.' },
  social:        { nom: 'Pressió social',      color: '#C2410C', descripcio: 'Entitats que visibilitzen, mobilitzen i fan pressió pública.' },
  sectorial:     { nom: 'Incidència sectorial',color: '#047857', descripcio: 'Organitzacions especialitzades (medi ambient, habitatge...).' },
};

const TERRITORI_META = {
  cat:    { nom: 'Catalunya',           descripcio: 'Canals i entitats amb seu i acció al Principat.' },
  bal:    { nom: 'Illes Balears',       descripcio: 'Canals i entitats amb seu a les Illes.' },
  val:    { nom: 'País Valencià',       descripcio: 'Canals i entitats amb seu al País Valencià.' },
  cn:     { nom: 'Catalunya Nord',      descripcio: 'Canals i entitats amb seu al Rosselló i comarques veïnes.' },
  and:    { nom: 'Andorra',             descripcio: 'Canals i entitats amb seu al Principat d\'Andorra.' },
  paisos: { nom: 'Països Catalans',     descripcio: 'Entitats transversals que actuen a tots els territoris.' },
};

const ENTITATS = [

  // ══════════════════════════════════════════
  //  ADMINISTRATIU
  // ══════════════════════════════════════════
  {
    id: 'sindic-greuges',
    nom: 'Síndic de Greuges de Catalunya',
    tipus: 'administratiu',
    ambit: 'Drets davant l\'administració',
    descripcio_breu: 'Defensa el ciutadà davant abusos o mal funcionament de l\'administració pública.',
    per_a_que: 'Fer que l\'administració es mogui quan no t\'ha respost, t\'ha tractat injustament, o un servei públic no funciona.',
    quan_usar: [
      'Un ajuntament o la Generalitat no et respon a un tràmit',
      'Tracte injust d\'una administració',
      'Un servei públic funciona malament',
      'Silenci administratiu',
    ],
    que_esperar: [
      'Obren una investigació del teu cas',
      'Fan recomanacions a l\'administració',
      'Seguiment institucional',
    ],
    punts_forts: ['Independent', 'Pressió formal efectiva', 'Gratuït'],
    limitacions: ['No pot sancionar', 'Procés lent', 'Les recomanacions no són obligatòries'],
    resultat_habitual: 'L\'administració revisa o rectifica el cas (no sempre).',
    temps: 'Setmanes / mesos',
    enllac: 'https://www.sindic.cat/ca/page.asp?id=65',
    pos:       [0.00, 0.00],
    pos_mobil: [0.00, 0.00],
  },
  {
    id: 'consum',
    nom: 'Agència Catalana del Consum',
    tipus: 'administratiu',
    ambit: 'Consumidors i empreses',
    descripcio_breu: 'Reclama davant empreses per serveis defectuosos, cobraments indeguts o contractes enganyosos.',
    per_a_que: 'Resoldre un conflicte amb una empresa o aconseguir que sigui sancionada per males pràctiques.',
    quan_usar: [
      'Cobraments indeguts',
      'Contractes enganyosos',
      'Productes o serveis defectuosos',
      'Telecos, llum, aigua, bancs...',
    ],
    que_esperar: [
      'Mediació amb l\'empresa',
      'Possible sanció administrativa',
    ],
    punts_forts: ['Molts casos es resolen', 'Via oficial reconeguda', 'Gratuït'],
    limitacions: ['Cal haver reclamat abans a l\'empresa', 'Lent'],
    resultat_habitual: 'Acord amb l\'empresa o resolució administrativa.',
    temps: 'Setmanes / mesos',
    enllac: 'https://consum.gencat.cat/ca/consultes-i-reclamacions/reclamacio-queixa-denuncia/',
    pos:       [0.333, 0.625],
    pos_mobil: [0.33, 0.40],
  },
  {
    id: 'catsalut',
    nom: 'Servei Català de la Salut',
    tipus: 'administratiu',
    ambit: 'Sanitat pública',
    descripcio_breu: 'Queixes sobre CAPs, hospitals, llistes d\'espera o errors sanitaris.',
    per_a_que: 'Fer arribar una queixa, reclamació o agraïment sobre l\'atenció sanitària rebuda.',
    quan_usar: [
      'Mala atenció al CAP o hospital',
      'Llistes d\'espera excessives',
      'Errors sanitaris o de gestió',
      'Problemes amb targeta sanitària',
    ],
    que_esperar: [
      'Resposta administrativa del centre o gerència',
      'Revisió del cas',
    ],
    punts_forts: ['Via oficial', 'Resposta formal'],
    limitacions: ['Ritme administratiu', 'No indemnitza directament'],
    resultat_habitual: 'Resposta del centre amb explicació o mesures correctores.',
    temps: 'Setmanes',
    enllac: 'https://ovt.gencat.cat/gsitfc/AppJava/generic/conqxsGeneric.do?webFormId=391&topicLevel1.id=1523&set-locale=ca_ES',
    pos:       [0.667, 0.125],
    pos_mobil: [0.67, 0.70],
  },
  {
    id: 'generalitat-instancia',
    nom: 'Generalitat — Instància genèrica',
    tipus: 'administratiu',
    ambit: 'Administració general',
    descripcio_breu: 'Canal universal quan no saps on dirigir-te dins l\'administració catalana.',
    per_a_que: 'Presentar una sol·licitud, queixa o suggeriment formal quan no hi ha un tràmit específic.',
    quan_usar: [
      'No saps a quin organisme correspon',
      'Sol·licituds genèriques',
      'Suggeriments o queixes internes',
    ],
    que_esperar: [
      'Derivació al departament competent',
      'Resposta formal (no sempre resolutiva)',
    ],
    punts_forts: ['Sempre disponible', 'Queda registrada oficialment'],
    limitacions: ['No resol directament', 'Pot tardar a arribar al destí correcte'],
    resultat_habitual: 'La sol·licitud es deriva i rebràs resposta del departament que correspongui.',
    temps: 'Setmanes',
    enllac: 'https://ovt.gencat.cat/gsitfc/AppJava/generic/conqxsGeneric.do?webFormId=31&topicLevel1.id=500&topicLevel2.id=624',
    pos:       [0.933, 0.375],
    pos_mobil: [0.83, 0.20],
  },

  // ══════════════════════════════════════════
  //  LEGAL
  // ══════════════════════════════════════════
  {
    id: 'antifrau',
    nom: 'Oficina Antifrau de Catalunya',
    tipus: 'legal',
    ambit: 'Corrupció i fons públics',
    descripcio_breu: 'Investiga corrupció, contractació irregular i ús indegut de recursos públics.',
    per_a_que: 'Posar en coneixement d\'un organisme independent sospites de corrupció o irregularitats a l\'administració.',
    quan_usar: [
      'Contractes públics sospitosos',
      'Ús irregular de diners públics',
      'Nepotisme o tracte de favor',
      'Conflictes d\'interès',
    ],
    que_esperar: [
      'Investigació confidencial',
      'Possible derivació a fiscalia',
      'Informes públics',
    ],
    punts_forts: ['Accepta denúncies anònimes', 'Independent', 'Alta capacitat d\'impacte'],
    limitacions: ['Cal certa base de proves', 'No tracta problemes personals petits'],
    resultat_habitual: 'Investigació interna i, si escau, trasllat al Ministeri Fiscal.',
    temps: 'Mesos',
    enllac: 'https://www.antifrau.cat/ca/investigacio/denuncieu.html',
    pos:       [0.20, 0.00],
    pos_mobil: [0.50, 0.10],
  },
  {
    id: 'mossos',
    nom: 'Mossos d\'Esquadra',
    tipus: 'legal',
    ambit: 'Delictes',
    descripcio_breu: 'Denúncia policial per delictes: robatoris, agressions, amenaces, delictes d\'odi.',
    per_a_que: 'Obrir via penal perquè un fet delictiu sigui investigat i, si escau, jutjat.',
    quan_usar: [
      'Robatoris, agressions físiques',
      'Amenaces, assetjament',
      'Delictes d\'odi o discriminació',
      'Violència masclista',
    ],
    que_esperar: [
      'Denúncia formal registrada',
      'Investigació policial',
      'Possible procés judicial',
    ],
    punts_forts: ['Imprescindible per delictes', 'Accés directe al sistema judicial'],
    limitacions: ['No resol conflictes administratius ni civils', 'Procés judicial pot ser llarg'],
    resultat_habitual: 'Atestat policial que passa al jutjat competent.',
    temps: 'Mesos / anys',
    enllac: 'https://ovt.gencat.cat/carpetaciutadana360/mfe-fc-app/gsitfc/AppJava/citpre/citpre.do?reqCode=simpleSearch&idTemaN2=29634',
    pos:       [0.533, 0.375],
    pos_mobil: [0.00, 0.30],
  },
  {
    id: 'apdcat',
    nom: 'Autoritat Catalana de Protecció de Dades',
    tipus: 'legal',
    ambit: 'Dades personals',
    descripcio_breu: 'Denúncia per ús indegut, filtracions o tractament abusiu de dades personals.',
    per_a_que: 'Fer que es sancioni una empresa o administració per vulnerar els teus drets de protecció de dades.',
    quan_usar: [
      'Filtracions de dades',
      'Ús de dades sense consentiment',
      'Videovigilància abusiva',
      'Spam o comunicacions no desitjades',
    ],
    que_esperar: [
      'Investigació formal',
      'Possibles sancions econòmiques',
    ],
    punts_forts: ['Molt efectiva', 'Pot imposar multes elevades'],
    limitacions: ['Només dades personals', 'Competència només sobre ens catalans'],
    resultat_habitual: 'Resolució amb sanció o advertiment al responsable.',
    temps: 'Mesos',
    enllac: 'https://www.apdcat.cat/ca/persones/reclama-i-denuncia',
    pos:       [0.067, 0.75],
    pos_mobil: [0.83, 0.50],
  },
  {
    id: 'jutjat-guardia',
    nom: 'Jutjat de Guàrdia — denúncia directa',
    tipus: 'legal',
    ambit: 'Via judicial penal',
    descripcio_breu: 'Presentar denúncia directament al jutjat sense passar per policia.',
    per_a_que: 'Iniciar un procés penal directament, útil quan vols controlar què es denuncia exactament.',
    quan_usar: [
      'Vols denunciar sense passar per Mossos',
      'Fets que requereixen actuació judicial urgent',
      'Delictes complexos on vols qualificació jurídica',
    ],
    que_esperar: [
      'Registre de la denúncia al jutjat',
      'Possible incoació de diligències',
    ],
    punts_forts: ['Més control sobre la redacció', 'Entrada directa al sistema judicial'],
    limitacions: ['Cal saber redactar-la bé (millor amb advocat)', 'No sempre accepten tots els casos'],
    resultat_habitual: 'Incoació de diligències prèvies o arxiu motivat.',
    temps: 'Mesos / anys',
    enllac: 'https://seujudicial.gencat.cat/ca/que_cal_fer/denuncia/',
    pos:       [0.867, 0.875],
    pos_mobil: [0.17, 0.80],
  },

  // ══════════════════════════════════════════
  //  LEGAL ESTRATÈGIC
  // ══════════════════════════════════════════
  {
    id: 'accio-cassandra',
    nom: 'Acció Cassandra',
    tipus: 'estrategic',
    ambit: 'Defensa de la nació catalana',
    descripcio_breu: 'Grup d\'advocats que porta casos judicials europeus en defensa de la minoria nacional catalana.',
    per_a_que: 'Impulsar procediments judicials (sovint europeus) per aconseguir el reconeixement jurídic de Catalunya com a nació minoritzada i perseguir delictes d\'odi contra catalans.',
    quan_usar: [
      'Delictes d\'odi contra persones per la seva condició de catalans',
      'Atacs al català com a llengua o al seu sistema educatiu',
      'Casos sobre el reconeixement jurídic d\'una nació minoritzada',
      'Vulneracions que requereixen via judicial internacional',
    ],
    que_esperar: [
      'Valoració legal del cas per part d\'advocats especialitzats',
      'Possible interposició de denúncies, querelles o procediments europeus',
      'Coordinació amb juristes d\'àmbit internacional',
    ],
    punts_forts: ['Focus en jurisdicció europea i drets de minories', 'Treball coordinat amb juristes internacionals', 'Voluntat de generar precedent jurídic'],
    limitacions: ['Casos seleccionats', 'Enfocats específicament en drets de la minoria nacional catalana', 'No és un canal massiu'],
    resultat_habitual: 'Procediments judicials amb voluntat de precedent i de reconeixement de drets.',
    temps: 'Mesos / anys',
    enllac: 'https://acciocassandra.cat/#denuncia',
    pos:       [0.20, 0.25],
    pos_mobil: [0.33, 0.20],
  },
  {
    id: 'iridia',
    nom: 'Irídia — Centre per la Defensa dels Drets Humans',
    tipus: 'estrategic',
    ambit: 'Drets humans',
    descripcio_breu: 'Defensa jurídica especialitzada en abusos policials i violència institucional.',
    per_a_que: 'Rebre assistència legal en casos de vulneració greu de drets humans per part d\'institucions.',
    quan_usar: [
      'Abusos policials',
      'Violència institucional',
      'Repressió de drets civils',
      'Casos amb component estructural',
    ],
    que_esperar: [
      'Assistència jurídica especialitzada',
      'Acompanyament al procés',
      'Litigis amb impacte',
    ],
    punts_forts: ['Alt impacte', 'Especialització reconeguda', 'Treball amb víctimes'],
    limitacions: ['Casos concrets i seleccionats', 'Recursos limitats'],
    resultat_habitual: 'Procediments judicials amb recorregut i incidència pública.',
    temps: 'Mesos / anys',
    enllac: 'https://iridia.cat/saidavi/',
    pos:       [0.467, 0.50],
    pos_mobil: [0.83, 0.80],
  },

  // ══════════════════════════════════════════
  //  PRESSIÓ SOCIAL
  // ══════════════════════════════════════════
  {
    id: 'plataforma-llengua',
    nom: 'Plataforma per la Llengua',
    tipus: 'social',
    ambit: 'Drets lingüístics',
    descripcio_breu: 'Defensa drets lingüístics davant empreses, administracions i situacions de discriminació.',
    per_a_que: 'Denunciar incompliments en matèria de català i fer que es moguin pressió política, mediàtica o legal.',
    quan_usar: [
      'Discriminació per parlar català',
      'Empreses que no respecten la llengua',
      'Administracions que no compleixen la normativa',
      'Incompliments a l\'etiquetatge, atenció al client...',
    ],
    que_esperar: [
      'Recollida i seguiment de la queixa',
      'Pressió pública o política',
      'Incidència (fins i tot internacional)',
    ],
    punts_forts: ['Molta incidència real', 'Aconsegueixen canvis normatius', 'Visibilitat'],
    limitacions: ['No resolen directament el cas individual', 'Depèn de volum de queixes'],
    resultat_habitual: 'Pressió sobre l\'empresa o administració i canvis progressius.',
    temps: 'Setmanes / mesos',
    enllac: 'https://www.queixes.plataforma-llengua.cat/',
    pos:       [0.00, 0.375],
    pos_mobil: [0.17, 0.50],
  },
  {
    id: 'omnium',
    nom: 'Òmnium Cultural',
    tipus: 'social',
    ambit: 'Drets civils i culturals',
    descripcio_breu: 'Defensa drets civils, culturals i col·lectius amb capacitat de mobilització.',
    per_a_que: 'Sumar-te o activar una causa col·lectiva que necessita mobilització i suport social.',
    quan_usar: [
      'Defensa de drets col·lectius',
      'Casos amb dimensió cultural o política',
      'Necessites mobilització social',
    ],
    que_esperar: [
      'Suport organitzatiu',
      'Campanyes públiques',
      'Pressió política',
    ],
    punts_forts: ['Gran base social', 'Capacitat mobilitzadora'],
    limitacions: ['No és un canal de queixa formal', 'Selecciona causes estratègiques'],
    resultat_habitual: 'Campanya pública o suport col·lectiu.',
    temps: 'Variable',
    enllac: 'https://www.omnium.cat/ca/contacte/',
    pos:       [0.60, 0.75],
    pos_mobil: [0.50, 0.70],
  },
  {
    id: 'facua',
    nom: 'FACUA Catalunya',
    tipus: 'social',
    ambit: 'Consumidors (contundent)',
    descripcio_breu: 'Defensa consumidors de forma més combativa: accions col·lectives i pressió mediàtica.',
    per_a_que: 'Sumar-te a accions col·lectives contra grans empreses o aconseguir visibilitat a un conflicte.',
    quan_usar: [
      'Conflictes amb grans empreses (telecos, bancs, elèctriques)',
      'Abusos que afecten molts consumidors',
      'Vols pressió mediàtica més enllà de la via administrativa',
    ],
    que_esperar: [
      'Assessorament si en ets soci/a',
      'Possible acció col·lectiva',
      'Pressió pública',
    ],
    punts_forts: ['Més contundent que Consum', 'Accions col·lectives'],
    limitacions: ['Serveis complets per a socis/es', 'No és institucional'],
    resultat_habitual: 'Denúncies públiques i, a vegades, sancions a empreses.',
    temps: 'Variable',
    enllac: 'https://facua.org/ca/cat/',
    pos:       [0.933, 0.00],
    pos_mobil: [0.83, 0.00],
  },

  // ══════════════════════════════════════════
  //  INCIDÈNCIA SECTORIAL
  // ══════════════════════════════════════════
  {
    id: 'observatori-desc',
    nom: 'Observatori DESC',
    tipus: 'sectorial',
    ambit: 'Habitatge i drets socials',
    descripcio_breu: 'Defensa drets econòmics, socials i culturals: habitatge, pobresa, desnonaments.',
    per_a_que: 'Rebre suport i incidència en vulneracions de drets socials amb component estructural.',
    quan_usar: [
      'Desnonaments',
      'Vulneració del dret a l\'habitatge',
      'Pobresa energètica',
      'Drets socials col·lectius',
    ],
    que_esperar: [
      'Incidència política i jurídica',
      'Suport en casos estructurals',
      'Informes i denúncia pública',
    ],
    punts_forts: ['Coneixement expert', 'Incidència institucional'],
    limitacions: ['No substitueix defensa jurídica individual'],
    resultat_habitual: 'Suport en casos col·lectius amb recorregut.',
    temps: 'Variable',
    enllac: 'https://observatoridesca.org/ca/contacte',
    pos:       [0.733, 0.50],
    pos_mobil: [0.67, 0.40],
  },
  {
    id: 'ecologistes-accio',
    hidden: true,
    nom: 'Ecologistes en Acció',
    tipus: 'sectorial',
    ambit: 'Medi ambient',
    descripcio_breu: 'Denúncia ambiental amb capacitat legal real: aturen projectes i guanyen judicis.',
    per_a_que: 'Denunciar impactes ambientals i donar-los recorregut legal i mediàtic.',
    quan_usar: [
      'Contaminació (aire, aigua, sòl)',
      'Urbanisme agressiu',
      'Projectes destructius (macrogranges, mines...)',
      'Incompliments de normativa ambiental',
    ],
    que_esperar: [
      'Accions legals si el cas ho justifica',
      'Campanyes públiques',
      'Informes tècnics',
    ],
    punts_forts: ['Aturen projectes reals', 'Base jurídica sòlida', 'Presència territorial'],
    limitacions: ['Prioritzen casos amb interès col·lectiu'],
    resultat_habitual: 'Bloqueig, modificació del projecte o sanció.',
    temps: 'Mesos / anys',
    enllac: 'https://www.ecologistasenaccion.org/areas-de-accion/comision-juridica/',
    pos:       [0.267, 0.875],
    pos_mobil: [0.50, 0.90],
  },

  // ══════════════════════════════════════════
  //  ADDICIONALS — AMB SEU ALS PAÏSOS CATALANS
  //  I WEB EN CATALÀ
  // ══════════════════════════════════════════
  {
    id: 'contenidor-rac1',
    nom: 'Contenidor — RAC1',
    tipus: 'social',
    ambit: 'Pressió mediàtica (consumidors)',
    descripcio_breu: 'Secció d\'El Món a RAC1 que recull queixes via WhatsApp, correu o telèfon i pressiona empreses en directe.',
    per_a_que: 'Enviar una queixa (preferiblement una nota de veu per WhatsApp al 669 10 10 10) i aconseguir que una empresa o administració reaccioni ràpid gràcies a la pressió mediàtica d\'un mitjà en català.',
    quan_usar: [
      'Empreses grans que no responen',
      'Conflictes repetits amb telecos, subministraments, transport…',
      'Casos amb possibilitat d\'impacte social',
    ],
    que_esperar: [
      'Possible emissió de la queixa al programa',
      'Reacció ràpida de l\'empresa implicada',
    ],
    punts_forts: ['Ràpid si la queixa és d\'interès', 'Format en català', 'Gran audiència'],
    limitacions: ['No totes les queixes s\'emeten', 'No és un canal oficial', 'També es pot contactar per correu (elmon@rac1.net) o telèfon 902 47 71 00'],
    resultat_habitual: 'L\'empresa contacta el ciutadà per resoldre el cas.',
    temps: 'Dies / setmanes',
    enllac: 'https://wa.me/34669101010',
    pos:       [0.40, 0.25],
    pos_mobil: [0.50, 0.30],
  },
  {
    id: 'sos-racisme',
    nom: 'SOS Racisme Catalunya',
    tipus: 'social',
    ambit: 'Racisme i xenofòbia',
    descripcio_breu: 'Denúncia i suport legal en casos de racisme, discriminació i delictes d\'odi.',
    per_a_que: 'Denunciar fets racistes, rebre suport jurídic i visibilitzar discriminacions estructurals.',
    quan_usar: [
      'Actes racistes o xenòfobs',
      'Discriminació per origen, color de pell o religió',
      'Abusos policials amb component racial',
      'Discurs d\'odi',
    ],
    que_esperar: [
      'Acompanyament jurídic del Servei d\'Atenció i Denúncia',
      'Inclusió del cas a l\'informe anual «Invisibles»',
      'Possible pressió pública',
    ],
    punts_forts: ['Especialització', 'Suport legal gratuït', 'Incidència estructural'],
    limitacions: ['Àmbit específic: racisme i xenofòbia'],
    resultat_habitual: 'Assessorament, denúncia si escau i inclusió a l\'informe de racisme a Catalunya.',
    temps: 'Setmanes',
    enllac: 'https://sosracisme.org/said/',
    pos:       [0.80, 0.625],
    pos_mobil: [0.00, 0.60],
  },
  {
    id: 'justicia-i-pau',
    nom: 'Justícia i Pau',
    tipus: 'social',
    ambit: 'Drets humans i pau',
    descripcio_breu: 'Entitat que defensa drets humans amb acompanyament jurídic i incidència política.',
    per_a_que: 'Rebre suport en vulneracions de drets humans, especialment en contextos penitenciaris, pau i persones migrants.',
    quan_usar: [
      'Vulneracions de drets humans',
      'Drets en context penitenciari',
      'Pau, no-violència i objecció',
      'Drets de persones migrants',
    ],
    que_esperar: [
      'Assessorament',
      'Acompanyament al procediment',
      'Incidència política i informes',
    ],
    punts_forts: ['Trajectòria llarga a Catalunya', 'Mirada integral de drets humans'],
    limitacions: ['No és un canal massiu de queixa formal'],
    resultat_habitual: 'Suport al cas i, si escau, denúncia pública o jurídica.',
    temps: 'Variable',
    enllac: 'https://www.justiciaipau.org/',
    pos:       [0.133, 0.50],
    pos_mobil: [0.83, 0.40],
  },
  {
    id: 'acpv',
    nom: 'Acció Cultural del País Valencià',
    tipus: 'social',
    ambit: 'Llengua i cultura catalanes al País Valencià',
    descripcio_breu: 'Entitat de referència per a la defensa del català i la cultura catalana al País Valencià.',
    per_a_que: 'Sumar-te o impulsar campanyes de defensa del català i dels drets lingüístics al País Valencià.',
    quan_usar: [
      'Incompliments en matèria de llengua al País Valencià',
      'Defensa de mitjans i ensenyament en català',
      'Activitats cíviques i culturals en català',
    ],
    que_esperar: [
      'Incidència política i cultural',
      'Campanyes i mobilitzacions',
    ],
    punts_forts: ['Trajectòria des de 1971', 'Gran base social al País Valencià', 'Web i activitat en català'],
    limitacions: ['No és un canal de queixa individual formal'],
    resultat_habitual: 'Pressió política, visibilitat i xarxa de suport.',
    temps: 'Variable',
    enllac: 'https://www.acpv.cat/contacte',
    pos:       [0.333, 0.375],
    pos_mobil: [0.33, 0.90],
  },
  {
    id: 'gepec',
    nom: 'GEPEC-EdC',
    tipus: 'sectorial',
    ambit: 'Medi ambient (ecosistemes catalans)',
    descripcio_breu: 'Grup d\'estudi i defensa d\'ecosistemes catalans amb capacitat de litigi i pressió territorial.',
    per_a_que: 'Denunciar impactes ambientals a Catalunya amb una entitat arrelada al territori i amb capacitat jurídica pròpia.',
    quan_usar: [
      'Contaminació industrial',
      'Projectes destructius al territori',
      'Afectacions a espais naturals de Catalunya',
      'Incompliments de normativa ambiental',
    ],
    que_esperar: [
      'Acompanyament tècnic',
      'Possibles accions legals',
      'Difusió pública',
    ],
    punts_forts: ['Arrel territorial (comarques de Tarragona)', 'Rigor tècnic', 'Capacitat jurídica'],
    limitacions: ['Focus a Catalunya', 'Recursos limitats'],
    resultat_habitual: 'Bloqueig o modificació de projectes, denúncia pública i administrativa.',
    temps: 'Mesos / anys',
    enllac: 'https://www.gepec.cat/',
    pos:       [0.80, 0.00],
    pos_mobil: [0.83, 0.60],
  },
  {
    id: 'politica-linguistica',
    nom: 'Direcció General de Política Lingüística',
    tipus: 'administratiu',
    ambit: 'Drets lingüístics (canal oficial)',
    descripcio_breu: 'Organisme de la Generalitat per a consultes, queixes i reclamacions sobre drets del català.',
    per_a_que: 'Fer arribar a la Generalitat una queixa o consulta oficial en matèria de llengua catalana.',
    quan_usar: [
      'Administracions o serveis públics que no respecten el català',
      'Incompliments normatius en matèria lingüística',
      'Dubtes sobre drets lingüístics',
    ],
    que_esperar: [
      'Resposta oficial de la Generalitat',
      'Derivació a l\'òrgan competent si escau',
    ],
    punts_forts: ['Canal oficial', 'Obligació de resposta administrativa'],
    limitacions: ['Competència limitada a Catalunya', 'No sanciona directament empreses privades'],
    resultat_habitual: 'Resposta administrativa, gestió interna o derivació.',
    temps: 'Setmanes',
    enllac: 'https://ovt.gencat.cat/gsitfc/AppJava/generic/conqxsGeneric.do?webFormId=11&set-locale=ca_ES',
    pos:       [0.20, 0.75],
    pos_mobil: [0.67, 0.10],
  },
  {
    id: 'accio-pel-catala',
    nom: 'Acció pel Català — Bot de queixes',
    tipus: 'social',
    ambit: 'Drets lingüístics (eina automatitzada)',
    descripcio_breu: 'Bot que automatitza la redacció i l\'enviament de queixes per incompliments en matèria de llengua catalana.',
    per_a_que: 'Enviar ràpidament queixes formals a empreses i administracions que no respecten el català, amb el text generat automàticament pel bot.',
    quan_usar: [
      'Empreses que no atenen en català',
      'Cartes, factures o etiquetatge sense català',
      'Serveis digitals que no ofereixen català',
      'Vols enviar queixes sense perdre temps redactant-les',
    ],
    que_esperar: [
      'El bot genera i envia la queixa',
      'Pressió acumulada amb altres queixes similars',
    ],
    punts_forts: ['Molt ràpid', 'Zero fricció per a l\'usuari', 'Web i servei en català'],
    limitacions: ['No és un canal oficial', 'Depèn que l\'empresa respongui'],
    resultat_habitual: 'Queixa enviada a l\'empresa; pressió acumulada amb la resta de queixes rebudes.',
    temps: 'Minuts',
    enllac: 'https://acciopelcatala.cat/bot-de-queixes/',
    pos:       [0.733, 0.25],
    pos_mobil: [0.00, 0.80],
  },
  {
    id: 'intersindical',
    nom: 'La Intersindical — Catalunya',
    tipus: 'social',
    ambit: 'Drets laborals (sindicat)',
    descripcio_breu: 'Sindicat català de classe per defensar els drets laborals i acompanyar en conflictes amb l\'empresa.',
    per_a_que: 'Rebre assessorament i suport sindical en conflictes laborals (acomiadaments, assetjament, impagaments, incompliments conveni...).',
    quan_usar: [
      'Acomiadament improcedent o nul',
      'Assetjament laboral o mobbing',
      'Incompliments del conveni col·lectiu',
      'Impagaments de salari o hores',
      'Necessites representació a l\'empresa',
    ],
    que_esperar: [
      'Assessorament sindical i jurídic',
      'Acompanyament al procés',
      'Possible via judicial via l\'assessoria laboral',
    ],
    punts_forts: ['Arrelament al territori', 'Sindicat en català', 'Combina defensa jurídica i pressió col·lectiva'],
    limitacions: ['Serveis complets sovint per afiliats'],
    resultat_habitual: 'Mediació, denúncia formal o judicialització del conflicte laboral.',
    temps: 'Setmanes / mesos',
    enllac: 'https://laintersindical.cat/contacte/',
    pos:       [0.20, 0.625],
    pos_mobil: [0.67, 0.60],
  },
  {
    id: 'oac-ajuntaments',
    nom: 'OAC — Oficines d\'Atenció Ciutadana',
    tipus: 'administratiu',
    ambit: 'Ajuntaments (tràmits i queixes locals)',
    descripcio_breu: 'Canal oficial del teu ajuntament per tràmits, queixes i suggeriments locals. Cada municipi té la seva.',
    per_a_que: 'Fer arribar al teu ajuntament una queixa, suggeriment o tràmit sobre serveis i afers municipals.',
    quan_usar: [
      'Espai públic: soroll, neteja, enllumenat, mobiliari...',
      'Serveis municipals (escoles bressol, esports, biblioteques...)',
      'Tributs i taxes locals',
      'Tràmits amb l\'ajuntament',
    ],
    que_esperar: [
      'Registre oficial de la sol·licitud',
      'Resposta administrativa del servei competent',
    ],
    punts_forts: ['Primer punt de contacte amb el municipi', 'Obligació de resposta administrativa'],
    limitacions: ['Només competències municipals', 'Cal conèixer el teu ajuntament'],
    resultat_habitual: 'Derivació al servei municipal corresponent i resposta formal.',
    temps: 'Setmanes',
    enllac: 'https://www.seu-e.cat/',
    pos:       [0.467, 0.875],
    pos_mobil: [0.50, 0.60],
  },

  // ══════════════════════════════════════════
  //  ILLES BALEARS
  // ══════════════════════════════════════════
  {
    id: 'sindic-ib',
    nom: 'Atenció a la Ciutadania — Govern de les Illes Balears',
    tipus: 'administratiu',
    ambit: 'Drets davant l\'administració (IB)',
    descripcio_breu: 'Canal oficial del Govern Balear per a queixes i suggeriments. El Síndic de Greuges IB mai s\'ha posat en marxa; aquesta és la via vigent.',
    per_a_que: 'Fer arribar una queixa, suggeriment o consulta al Govern de les Illes Balears quan no et responen o actuen malament.',
    quan_usar: [
      'Silenci administratiu del Govern Balear o ajuntaments IB',
      'Serveis públics insulars que funcionen malament',
      'Tracte injust d\'una administració balear',
    ],
    que_esperar: [
      'Registre oficial de la queixa',
      'Resposta administrativa del servei competent',
    ],
    punts_forts: ['Canal oficial operatiu', 'Obligació de resposta'],
    limitacions: ['No és un defensor independent com un síndic', 'La Sindicatura de Greuges IB mai s\'ha arribat a constituir'],
    resultat_habitual: 'Resposta administrativa o derivació al servei competent. Per a casos greus cal recórrer al Defensor del Pueblo.',
    temps: 'Setmanes',
    enllac: 'https://www.caib.es/sites/queixesisuggeriments/ca/queixes_telematica/',
    pos:       [0.533, 0.125],
    pos_mobil: [0.67, 0.30],
  },
  {
    id: 'oficina-prevencio-ib',
    nom: 'Oficina de Prevenció i Lluita contra la Corrupció IB',
    tipus: 'legal',
    ambit: 'Corrupció i fons públics (IB)',
    descripcio_breu: 'Investiga corrupció i irregularitats a l\'administració balear.',
    per_a_que: 'Denunciar corrupció, contractació irregular o ús indegut de recursos públics a les Illes Balears.',
    quan_usar: [
      'Contractes públics sospitosos a IB',
      'Nepotisme o tracte de favor a administracions balears',
      'Ús irregular de diners públics',
    ],
    que_esperar: [
      'Investigació confidencial',
      'Possible trasllat a fiscalia',
    ],
    punts_forts: ['Admet denúncies anònimes', 'Independència'],
    limitacions: ['Requereix base de proves', 'Àmbit només IB'],
    resultat_habitual: 'Investigació i, si escau, accions legals.',
    temps: 'Mesos',
    enllac: 'https://www.oaib.es/ca/denuncies/',
    enllac_inactiu: true,
    pos:       [0.40, 0.50],
    pos_mobil: [0.33, 0.60],
  },
  {
    id: 'ocb',
    nom: 'Obra Cultural Balear (OCB)',
    tipus: 'social',
    ambit: 'Llengua i cultura catalanes (IB)',
    descripcio_breu: 'Entitat de referència per a la defensa de la llengua i la cultura catalanes a les Illes Balears.',
    per_a_que: 'Impulsar campanyes i donar suport en matèria de llengua i cultura catalanes a les Balears.',
    quan_usar: [
      'Incompliments normatius en matèria de català a IB',
      'Defensa de l\'ensenyament en català',
      'Drets lingüístics al dia a dia',
    ],
    que_esperar: [
      'Acompanyament i incidència política',
      'Campanyes públiques',
    ],
    punts_forts: ['Gran base social a les Illes', 'Trajectòria llarga'],
    limitacions: ['No és un canal formal de queixa'],
    resultat_habitual: 'Pressió i xarxa de suport.',
    temps: 'Variable',
    enllac: 'https://ocb.cat/contacte/',
    pos:       [0.667, 0.625],
    pos_mobil: [0.67, 0.80],
  },
  {
    id: 'gob',
    nom: 'GOB — Grup Balear d\'Ornitologia',
    tipus: 'sectorial',
    ambit: 'Medi ambient (Illes Balears)',
    descripcio_breu: 'Grup ecologista referent a les Illes, amb capacitat de litigi i incidència territorial.',
    per_a_que: 'Denunciar impactes ambientals a les Illes Balears amb una entitat arrelada amb capacitat jurídica.',
    quan_usar: [
      'Urbanisme agressiu a les Illes',
      'Impactes a espais naturals balears',
      'Incompliments de normativa ambiental',
    ],
    que_esperar: [
      'Acompanyament tècnic',
      'Possibles accions legals',
      'Difusió pública',
    ],
    punts_forts: ['Arrelament territorial', 'Capacitat jurídica', 'Trajectòria'],
    limitacions: ['Focus Illes Balears'],
    resultat_habitual: 'Bloqueig o modificació de projectes, denúncia pública.',
    temps: 'Mesos / anys',
    enllac: 'https://www.gobmallorca.com/denuncia/',
    pos:       [0.133, 0.875],
    pos_mobil: [0.17, 0.20],
  },

  // ══════════════════════════════════════════
  //  PAÍS VALENCIÀ
  // ══════════════════════════════════════════
  {
    id: 'sindic-cv',
    nom: 'Síndic de Greuges de la Comunitat Valenciana',
    tipus: 'administratiu',
    ambit: 'Drets davant l\'administració (PV)',
    descripcio_breu: 'Defensor del ciutadà davant les administracions del País Valencià.',
    per_a_que: 'Reclamar davant la Generalitat Valenciana o els ajuntaments del País Valencià.',
    quan_usar: [
      'Silenci administratiu al PV',
      'Serveis públics valencians mal gestionats',
      'Tracte injust d\'una administració valenciana',
    ],
    que_esperar: [
      'Investigació del cas',
      'Recomanacions a l\'administració',
    ],
    punts_forts: ['Independent', 'Cobertura específica del PV'],
    limitacions: ['No pot sancionar'],
    resultat_habitual: 'Revisió o rectificació administrativa (no sempre).',
    temps: 'Setmanes / mesos',
    enllac: 'https://www.elsindic.com/te-ayudamos/presentar-una-queja-consulta/',
    pos:       [0.867, 0.125],
    pos_mobil: [0.00, 0.20],
  },
  {
    id: 'agencia-valenciana-antifrau',
    nom: 'Agència Valenciana Antifrau',
    tipus: 'legal',
    ambit: 'Corrupció i fons públics (PV)',
    descripcio_breu: 'Investiga corrupció i irregularitats a les administracions del País Valencià.',
    per_a_que: 'Denunciar corrupció o ús indegut de recursos públics al País Valencià.',
    quan_usar: [
      'Contractes públics sospitosos al PV',
      'Nepotisme o tracte de favor',
      'Ús irregular de diners públics',
    ],
    que_esperar: [
      'Investigació confidencial',
      'Possible trasllat a fiscalia',
    ],
    punts_forts: ['Canal de denúncia protegit', 'Independència'],
    limitacions: ['Àmbit només PV'],
    resultat_habitual: 'Investigació i, si escau, accions legals.',
    temps: 'Mesos',
    enllac: 'https://www.antifraucv.es/va/bustia-de-denuncies-2/',
    pos:       [0.733, 0.75],
    pos_mobil: [0.67, 0.90],
  },
  {
    id: 'escola-valenciana',
    nom: 'Escola Valenciana',
    tipus: 'social',
    ambit: 'Ensenyament en valencià (PV)',
    descripcio_breu: 'Federació d\'entitats que defensa l\'ensenyament i els drets lingüístics en valencià.',
    per_a_que: 'Sumar-te o denunciar incompliments a l\'ensenyament en valencià i drets lingüístics al PV.',
    quan_usar: [
      'Problemes amb ensenyament en valencià',
      'Vulneracions de drets lingüístics al PV',
      'Defensa de la llengua al sistema educatiu',
    ],
    que_esperar: [
      'Incidència política',
      'Campanyes i mobilitzacions',
    ],
    punts_forts: ['Referent educatiu al PV', 'Base social àmplia'],
    limitacions: ['No és un canal de queixa individual formal'],
    resultat_habitual: 'Pressió política i visibilitat.',
    temps: 'Variable',
    enllac: 'https://escolavalenciana.org/contacte-valencia/',
    pos:       [0.267, 0.125],
    pos_mobil: [0.33, 0.00],
  },
  {
    id: 'accio-ecologista-agro',
    nom: 'Acció Ecologista-Agró',
    tipus: 'sectorial',
    ambit: 'Medi ambient (País Valencià)',
    descripcio_breu: 'Entitat ecologista de referència al País Valencià, amb capacitat jurídica i territorial.',
    per_a_que: 'Denunciar impactes ambientals al País Valencià amb suport tècnic i jurídic.',
    quan_usar: [
      'Contaminació o impactes ambientals al PV',
      'Projectes destructius al territori',
      'Afectacions a espais naturals valencians',
    ],
    que_esperar: [
      'Acompanyament tècnic',
      'Possibles accions legals',
      'Difusió pública',
    ],
    punts_forts: ['Arrelament territorial', 'Trajectòria'],
    limitacions: ['Focus País Valencià'],
    resultat_habitual: 'Bloqueig o modificació de projectes, denúncia pública.',
    temps: 'Mesos / anys',
    enllac: 'https://accioecologista-agro.org/contacte/',
    pos:       [0.60, 0.25],
    pos_mobil: [0.83, 0.20],
  },

  // ══════════════════════════════════════════
  //  CATALUNYA NORD
  // ══════════════════════════════════════════
  {
    id: 'aplec',
    nom: 'APLEC — Catalunya Nord',
    tipus: 'social',
    ambit: 'Ensenyament del català (Catalunya Nord)',
    descripcio_breu: 'Associació per l\'ensenyament del català a la Catalunya Nord.',
    per_a_que: 'Donar suport i denunciar dificultats en l\'ensenyament del català a la Catalunya Nord.',
    quan_usar: [
      'Problemes amb l\'ensenyament del català al nord',
      'Defensa de la llengua en àmbits educatius i socials',
    ],
    que_esperar: [
      'Acompanyament',
      'Campanyes i incidència',
    ],
    punts_forts: ['Referent a la Catalunya Nord', 'Web en català'],
    limitacions: ['Àmbit geogràfic concret'],
    resultat_habitual: 'Pressió i visibilitat.',
    temps: 'Variable',
    enllac: 'https://aplec.cat/contacteu/',
    pos:       [0.533, 0.875],
    pos_mobil: [0.67, 0.20],
  },

  // ══════════════════════════════════════════
  //  ANDORRA
  // ══════════════════════════════════════════
  {
    id: 'raonador-andorra',
    nom: 'Raonador del Ciutadà d\'Andorra',
    tipus: 'administratiu',
    ambit: 'Drets davant l\'administració (Andorra)',
    descripcio_breu: 'Defensor del ciutadà davant les administracions del Principat d\'Andorra.',
    per_a_que: 'Reclamar davant les administracions andorranes quan es vulneren drets o no responen.',
    quan_usar: [
      'Silenci administratiu a Andorra',
      'Serveis públics andorrans mal gestionats',
      'Tracte injust d\'una administració andorrana',
    ],
    que_esperar: [
      'Investigació del cas',
      'Recomanacions a l\'administració',
    ],
    punts_forts: ['Independent', 'Cobertura específica d\'Andorra'],
    limitacions: ['No pot sancionar'],
    resultat_habitual: 'Revisió o rectificació administrativa.',
    temps: 'Setmanes / mesos',
    enllac: 'https://forms.cloud.microsoft/e/ahhCVauT00?lang=ca-ES',
    pos:       [0.067, 0.625],
    pos_mobil: [0.33, 0.70],
  },
  {
    id: 'ibsalut',
    nom: 'Servei de Salut de les Illes Balears (IbSalut)',
    tipus: 'administratiu',
    ambit: 'Sanitat pública (IB)',
    descripcio_breu: 'Queixes sobre CAPs, hospitals, llistes d\'espera o errors sanitaris a les Illes Balears.',
    per_a_que: 'Fer arribar una queixa sobre l\'atenció sanitària pública a les Illes.',
    quan_usar: [
      'Mala atenció al CAP o hospital a IB',
      'Llistes d\'espera excessives',
      'Errors sanitaris o de gestió',
      'Problemes amb targeta sanitària IB',
    ],
    que_esperar: [
      'Resposta del centre o gerència',
      'Revisió del cas',
    ],
    punts_forts: ['Via oficial', 'Obligació de resposta'],
    limitacions: ['Ritme administratiu', 'No indemnitza directament'],
    resultat_habitual: 'Resposta del centre amb explicació o mesures correctores.',
    temps: 'Setmanes',
    enllac: 'https://www.caib.es/sistrafront/sistrafront/protected/init.do?language=ca&modelo=IN0008IBSA&version=2',
    pos:       [0.80, 0.375],
    pos_mobil: [0.17, 0.10],
  },
  {
    id: 'ibavi',
    nom: 'Institut Balear de l\'Habitatge (IBAVI)',
    tipus: 'administratiu',
    ambit: 'Habitatge públic (IB)',
    descripcio_breu: 'Queixes i consultes sobre habitatge públic, ajudes i drets a les Illes Balears.',
    per_a_que: 'Fer arribar queixes o consultes sobre polítiques d\'habitatge del Govern Balear.',
    quan_usar: [
      'Problemes amb habitatge de protecció oficial',
      'Ajudes al lloguer a IB',
      'Drets d\'habitatge',
    ],
    que_esperar: [
      'Resposta administrativa de l\'IBAVI',
      'Derivació al servei competent',
    ],
    punts_forts: ['Canal oficial específic', 'Obligació de resposta'],
    limitacions: ['Només temes d\'habitatge IB'],
    resultat_habitual: 'Resposta formal o derivació.',
    temps: 'Setmanes',
    enllac: 'https://www.caib.es/sites/habitatges/ca/fcontacto/queixes_suggeriments_agraiments/',
    pos:       [0.333, 0.00],
    pos_mobil: [0.50, 0.00],
  },
  {
    id: 'drets-linguistics-ib',
    nom: 'Oficina de Defensa dels Drets Lingüístics (IB)',
    tipus: 'administratiu',
    ambit: 'Drets lingüístics (IB, canal oficial)',
    descripcio_breu: 'Organisme del Govern Balear per a denúncies sobre drets del català a les Illes.',
    per_a_que: 'Fer arribar al Govern Balear una queixa oficial en matèria de català.',
    quan_usar: [
      'Administracions o serveis que no respecten el català a IB',
      'Incompliments normatius en matèria lingüística',
      'Discriminació per parlar català',
    ],
    que_esperar: [
      'Investigació i resposta oficial',
      'Derivació a l\'òrgan competent',
    ],
    punts_forts: ['Canal oficial específic', 'Obligació de resposta'],
    limitacions: ['Competència només a les Illes'],
    resultat_habitual: 'Resposta o mesures correctores segons el cas.',
    temps: 'Setmanes',
    enllac: 'http://www.caib.cat/sites/oficinadretslinguistics/ca/acces_al_tramit_telematic/',
    pos:       [0.40, 0.75],
    pos_mobil: [0.00, 0.40],
  },
  {
    id: 'consum-ib',
    nom: 'Consum — Illes Balears',
    tipus: 'administratiu',
    ambit: 'Consumidors i empreses (IB)',
    descripcio_breu: 'Reclamacions, denúncies i consultes de consum a les Illes Balears.',
    per_a_que: 'Reclamar davant empreses per serveis o productes defectuosos a les Illes.',
    quan_usar: [
      'Cobraments indeguts a IB',
      'Contractes enganyosos',
      'Serveis defectuosos (telecos, llum, aigua, bancs...)',
    ],
    que_esperar: [
      'Mediació amb l\'empresa',
      'Possible sanció administrativa',
    ],
    punts_forts: ['Molts casos es resolen', 'Via oficial reconeguda'],
    limitacions: ['Cal haver reclamat abans a l\'empresa', 'Lent'],
    resultat_habitual: 'Acord amb l\'empresa o resolució administrativa.',
    temps: 'Setmanes / mesos',
    enllac: 'http://www.caib.es/sites/consumidor/ca/reclamaciones_denuncias_y_consultas-90/',
    pos:       [0.60, 0.50],
    pos_mobil: [0.17, 0.90],
  },
  {
    id: 'tib-transports-ib',
    nom: 'Transports de les Illes Balears (TIB)',
    tipus: 'administratiu',
    ambit: 'Transport públic (IB)',
    descripcio_breu: 'Reclamacions i suggeriments sobre el transport públic de les Illes Balears.',
    per_a_que: 'Fer arribar una queixa o suggeriment al consorci de transports balear (TIB).',
    quan_usar: [
      'Incidències amb bus, metro, ferrocarril IB',
      'Horaris, puntualitat, atenció',
      'Accessibilitat al transport públic',
    ],
    que_esperar: [
      'Resposta del consorci',
      'Possible rectificació del servei',
    ],
    punts_forts: ['Canal específic del servei', 'Obligació de resposta'],
    limitacions: ['Només transport IB'],
    resultat_habitual: 'Resposta o mesura correctora.',
    temps: 'Dies / setmanes',
    enllac: 'https://www.tib.org/web/ctm/reclamacions-i-suggeriments',
    pos:       [0.133, 0.25],
    pos_mobil: [0.00, 0.70],
  },
  {
    id: 'accessibilitat-ib',
    nom: 'Accessibilitat de webs i apps (IB)',
    tipus: 'administratiu',
    ambit: 'Accessibilitat digital (IB)',
    descripcio_breu: 'Queixes per incompliment de requisits d\'accessibilitat en webs i apps públiques de les Illes.',
    per_a_que: 'Denunciar que una web o app pública del Govern Balear no és accessible per a persones amb discapacitat.',
    quan_usar: [
      'Webs/apps del Govern Balear no accessibles',
      'Documents no accessibles amb lector de pantalla',
      'Problemes d\'accessibilitat digital en serveis públics IB',
    ],
    que_esperar: [
      'Resposta de l\'òrgan responsable',
      'Possibles correccions tècniques',
    ],
    punts_forts: ['Canal oficial per accessibilitat', 'Regulat per normativa europea'],
    limitacions: ['Només webs/apps públiques IB'],
    resultat_habitual: 'Adaptació o justificació del responsable.',
    temps: 'Setmanes',
    enllac: 'https://www.caib.es/sistrafront/sistrafront/inicio?language=ca&modelo=IN0014CON&version=1',
    pos:       [0.267, 0.50],
    pos_mobil: [0.83, 0.90],
  },
  {
    id: 'ecologistes-accio-pv',
    hidden: true,
    nom: 'Ecologistes en Acció — Federació del País Valencià',
    tipus: 'sectorial',
    ambit: 'Medi ambient (País Valencià)',
    descripcio_breu: 'Federació d\'Ecologistes en Acció al País Valencià, amb capacitat jurídica i presència territorial.',
    per_a_que: 'Denunciar impactes ambientals al País Valencià amb una federació arrelada i amb capacitat d\'acció legal.',
    quan_usar: [
      'Contaminació o impactes ambientals al PV',
      'Projectes destructius al territori valencià',
      'Afectacions a espais naturals',
      'Incompliments normativa ambiental',
    ],
    que_esperar: [
      'Acompanyament tècnic',
      'Possibles accions legals (via Comissió Jurídica)',
      'Difusió pública',
    ],
    punts_forts: ['Presència territorial al PV', 'Suport jurídic estatal', 'Experiència en litigi ambiental'],
    limitacions: ['Prioritzen casos d\'interès col·lectiu'],
    resultat_habitual: 'Bloqueig o modificació de projectes, denúncia pública.',
    temps: 'Mesos / anys',
    enllac: 'https://www.ecologistasenaccion.org/areas-de-accion/comision-juridica/',
    pos:       [0.40, 0.625],
    pos_mobil: [0.17, 0.70],
  },

];

// ─── Assignació de territori per a cada entitat ────────
const _TERRITORI_BY_ID = {
  // Catalunya (Principat)
  'sindic-greuges':         'cat',
  'consum':                 'cat',
  'catsalut':               'cat',
  'generalitat-instancia':  'cat',
  'politica-linguistica':   'cat',
  'oac-ajuntaments':        'cat',
  'antifrau':               'cat',
  'mossos':                 'cat',
  'apdcat':                 'cat',
  'jutjat-guardia':         'cat',
  'iridia':                 'cat',
  'omnium':                 'cat',
  'facua':                  'cat',
  'observatori-desc':       'cat',
  'ecologistes-accio':      'cat',
  'intersindical':          'cat',
  'contenidor-rac1':        'cat',
  'sos-racisme':            'cat',
  'justicia-i-pau':         'cat',
  'gepec':                  'cat',

  // Illes Balears
  'sindic-ib':              'bal',
  'oficina-prevencio-ib':   'bal',
  'ocb':                    'bal',
  'gob':                    'bal',
  'ibsalut':                'bal',
  'ibavi':                  'bal',
  'drets-linguistics-ib':   'bal',
  'consum-ib':              'bal',
  'tib-transports-ib':      'bal',
  'accessibilitat-ib':      'bal',

  // País Valencià
  'acpv':                   'val',
  'sindic-cv':              'val',
  'agencia-valenciana-antifrau': 'val',
  'escola-valenciana':      'val',
  'accio-ecologista-agro':  'val',

  // Catalunya Nord
  'aplec':                  'cn',

  // Afegits posteriors
  'ecologistes-accio-pv':   'val',

  // Andorra
  'raonador-andorra':       'and',

  // Transversals (Països Catalans)
  'plataforma-llengua':     'paisos',
  'accio-cassandra':        'paisos',
  'accio-pel-catala':       'paisos',
};
ENTITATS.forEach(e => { e.territori = _TERRITORI_BY_ID[e.id] || 'cat'; });

// ─── Adreces i telèfons ───────────────────────────────
// Ús: si adreca o telefon estan buits ('—' o ''), la UI no els mostrarà.
const _CONTACTE_BY_ID = {
  'sindic-greuges':         { adreca: 'Passeig de Lluís Companys, 7, 08003 Barcelona', telefon: '900 124 124' },
  'consum':                 { adreca: 'Carrer del Foc, 57, 08038 Barcelona',             telefon: '93 857 40 00' },
  'catsalut':               { adreca: 'Travessera de les Corts, 131-159, Edifici Olímpia, 08028 Barcelona', telefon: '93 403 85 85' },
  'generalitat-instancia':  { adreca: '',                                                 telefon: '012' },
  'politica-linguistica':   { adreca: '',                                                 telefon: '012' },
  'oac-ajuntaments':        { adreca: '',                                                 telefon: '012' },
  'antifrau':               { adreca: 'Carrer de Ribes, 1-3, 08013 Barcelona',            telefon: '93 554 55 55' },
  'mossos':                 { adreca: '',                                                 telefon: '112 (emergències)' },
  'apdcat':                 { adreca: 'Gran Via de les Corts Catalanes, 635, 08010 Barcelona', telefon: '93 552 78 00' },
  'jutjat-guardia':         { adreca: '',                                                 telefon: '900 12 18 84 (víctimes)' },
  'accio-cassandra':        { adreca: '',                                                 telefon: '' },
  'iridia':                 { adreca: 'Riera d\'Escuder, 38 Nau 1 baixos, 08028 Barcelona', telefon: '693 287 323' },
  'plataforma-llengua':     { adreca: 'Carrer de Sant Honorat, 7 Principal 1a, 08002 Barcelona', telefon: '93 321 18 03' },
  'omnium':                 { adreca: 'Carrer de la Diputació, 276, pral., 08009 Barcelona', telefon: '93 319 80 50' },
  'facua':                  { adreca: 'Carrer de Leiva, 25, 08014 Barcelona',              telefon: '688 954 954' },
  'observatori-desc':       { adreca: 'Carrer de Casp, 43, baixos, 08010 Barcelona',       telefon: '93 302 68 82' },
  'ecologistes-accio':      { adreca: 'Carrer d\'Olzinelles, 31, 08014 Barcelona',         telefon: '648 76 11 99' },
  'intersindical':          { adreca: 'Carrer de Rocafort, 242 bis, 08029 Barcelona',      telefon: '93 481 36 60' },
  'contenidor-rac1':        { adreca: '',                                                 telefon: '669 10 10 10 (WhatsApp)' },
  'sos-racisme':            { adreca: 'Carrer de Maria Casas Mira, 38, 08001 Barcelona',   telefon: '652 87 34 06' },
  'justicia-i-pau':         { adreca: 'Carrer de Roger de Llúria, 126, 3r 1a, 08037 Barcelona', telefon: '622 561 495' },
  'acpv':                   { adreca: 'Carrer de Sant Ferran, 12, 46001 València',         telefon: '96 315 77 99' },
  'gepec':                  { adreca: '',                                                 telefon: '977 33 11 42' },
  'accio-pel-catala':       { adreca: '',                                                 telefon: '' },
  'sindic-ib':              { adreca: '',                                                 telefon: '012' },
  'oficina-prevencio-ib':   { adreca: 'Carrer d\'Antoni Marquès Marquès, 11, 07003 Palma',  telefon: '971 72 00 04' },
  'ocb':                    { adreca: 'Carrer de Sant Alonso, 24, 07001 Palma',            telefon: '971 72 32 99' },
  'gob':                    { adreca: 'Carrer de Manuel Sanchis Guarner, 10, 07004 Palma', telefon: '971 49 60 60' },
  'sindic-cv':              { adreca: 'Carrer Pascual Blasco, 1, 03001 Alacant',           telefon: '900 210 970' },
  'agencia-valenciana-antifrau': { adreca: 'Carrer Navellos, 14, porta 3, 46003 València', telefon: '96 278 74 50' },
  'escola-valenciana':      { adreca: 'Carrer d\'Antoni Maura, 18 baix, 12001 Castelló de la Plana', telefon: '659 04 13 95' },
  'accio-ecologista-agro':  { adreca: 'Portal de Valldigna, 15, 46003 València',           telefon: '96 391 78 64' },
  'aplec':                  { adreca: 'Universitat de Perpinyà, P1, Casa dels Països Catalans, Camí de la Passió Vella, 66860 Perpinyà Cedex', telefon: '+33 4 68 66 22 11' },
  'raonador-andorra':       { adreca: '',                                                 telefon: '+376 180 030 30' },
  'ecologistes-accio-pv':   { adreca: '',                                                 telefon: '96 525 52 70' },
  'ibsalut':                { adreca: '',                                                 telefon: '971 17 56 00' },
  'ibavi':                  { adreca: '',                                                 telefon: '971 78 49 90' },
  'drets-linguistics-ib':   { adreca: '',                                                 telefon: '012' },
  'consum-ib':              { adreca: '',                                                 telefon: '971 17 65 58' },
  'tib-transports-ib':      { adreca: '',                                                 telefon: '971 17 77 77' },
  'accessibilitat-ib':      { adreca: '',                                                 telefon: '012' },
};
ENTITATS.forEach(e => {
  const c = _CONTACTE_BY_ID[e.id] || {};
  e.adreca = c.adreca || '';
  e.telefon = c.telefon || '';
});

// ─── Sigles per mostrar a les icones (prioritza les oficials quan existeixen) ───
const _SIGLES_BY_ID = {
  // Catalunya
  'sindic-greuges':         'SG',
  'consum':                 'ACC',
  'catsalut':               'SCS',
  'generalitat-instancia':  'GEN',
  'politica-linguistica':   'DGPL',
  'oac-ajuntaments':        'OAC',
  'antifrau':               'OAF',
  'mossos':                 'MdE',
  'apdcat':                 'APDC',
  'jutjat-guardia':         'JG',
  'accio-cassandra':        'Cass',
  'iridia':                 'IRI',
  'plataforma-llengua':     'PxLl',
  'intersindical':          'IS',
  'omnium':                 'ÒC',
  'facua':                  'FACUA',
  'observatori-desc':       'DESC',
  'ecologistes-accio':      'EeA',
  'contenidor-rac1':        'RAC1',
  'sos-racisme':            'SOS',
  'justicia-i-pau':         'J&P',
  'gepec':                  'GEPEC',
  'accio-pel-catala':       'APC',

  // Balears
  'sindic-ib':              'CAIB',
  'oficina-prevencio-ib':   'OAIB',
  'ocb':                    'OCB',
  'gob':                    'GOB',
  'ibsalut':                'IBS',
  'ibavi':                  'IBAVI',
  'drets-linguistics-ib':   'ODL',
  'consum-ib':              'CIB',
  'tib-transports-ib':      'TIB',
  'accessibilitat-ib':      'A11',

  // País Valencià
  'acpv':                   'ACPV',
  'sindic-cv':              'SCV',
  'agencia-valenciana-antifrau': 'AVA',
  'escola-valenciana':      'EV',
  'accio-ecologista-agro':  'Agró',
  'ecologistes-accio-pv':   'EePV',

  // Catalunya Nord
  'aplec':                  'APL',

  // Andorra
  'raonador-andorra':       'Raon',
};
ENTITATS.forEach(e => { e.sigles = _SIGLES_BY_ID[e.id] || e.nom.charAt(0).toUpperCase(); });
