/**
 * ENTITATS DE DENUNCIEM.CAT
 * ────────────────────────
 * Cada entitat és una fitxa estàndard amb els mateixos camps.
 *
 * Camps:
 *   id                slug únic (per enllaç directe)
 *   nom               nom complet
 *   tipus             'administratiu' | 'legal' | 'estrategic' | 'social' | 'sectorial'
 *   ambit             categoria temàtica (lliure, curta)
 *   descripcio_breu   1 línia — es mostra a la targeta del grid
 *   per_a_que         1-2 frases — què aconsegueix l'usuari
 *   quan_usar         array d'ítems — casos concrets
 *   que_esperar       array d'ítems — què passarà després
 *   punts_forts       array d'ítems
 *   limitacions       array d'ítems
 *   resultat_habitual 1 frase
 *   temps             orientatiu ('Dies', 'Setmanes', 'Setmanes / mesos', 'Mesos', 'Mesos / anys')
 *   enllac            URL directe al formulari / canal / contacte
 *   pos               [col_rel, row_rel] de 0 a 1 — posició al grid d'escriptori (10×6)
 *   pos_mobil         [col_rel, row_rel] de 0 a 1 — posició al grid mòbil (6×10)
 *
 * Per afegir-ne: copia un bloc, canvia els camps i comprova que l'id sigui únic.
 */

const TIPUS_META = {
  administratiu: { nom: 'Administratiu',       color: '#2563EB', descripcio: 'Canals oficials que supervisen o resolen davant l\'administració i empreses.' },
  legal:         { nom: 'Legal',               color: '#B91C1C', descripcio: 'Via penal, sancionadora o d\'investigació oficial.' },
  estrategic:    { nom: 'Legal estratègic',    color: '#7C2D12', descripcio: 'Accions judicials amb voluntat d\'impacte i precedent.' },
  social:        { nom: 'Pressió social',      color: '#C2410C', descripcio: 'Entitats que visibilitzen, mobilitzen i fan pressió pública.' },
  sectorial:     { nom: 'Incidència sectorial',color: '#047857', descripcio: 'Organitzacions especialitzades (medi ambient, habitatge...).' },
};

const TERRITORI_META = {
  cat:    { nom: 'Catalunya del Sud',   descripcio: 'Canals i entitats amb seu i acció al Principat.' },
  bal:    { nom: 'Illes Balears',       descripcio: 'Canals i entitats amb seu a les Illes.' },
  val:    { nom: 'País Valencià',       descripcio: 'Canals i entitats amb seu al País Valencià.' },
  cn:     { nom: 'Catalunya Nord',      descripcio: 'Canals i entitats amb seu al Rosselló i comarques veïnes.' },
  and:    { nom: 'Andorra',             descripcio: 'Canals i entitats amb seu al Principat d\'Andorra.' },
  franja: { nom: 'Franja de Ponent',    descripcio: 'Comarques orientals de l\'Aragó de parla catalana.' },
  alguer: { nom: 'l\'Alguer',           descripcio: 'Ciutat catalanoparlant de Sardenya.' },
  carxe:  { nom: 'El Carxe',            descripcio: 'Territori catalanoparlant al nord-est de Múrcia.' },
  paisos:   { nom: 'Països Catalans',  descripcio: 'Entitats transversals que actuen a tots els territoris.' },
  mesenlla: { nom: 'Més enllà',        descripcio: 'Entitats que poden ajudar si ets fora dels Països Catalans (resta del món).' },
};

// Temàtiques del problema (per a la pregunta «De què es tracta?»)
const TEMATIQUES_META = {
  admin:         { nom: 'Administració no em respon',   descripcio: 'Silenci o mal funcionament d\'una administració pública.' },
  consum:        { nom: 'Consum i empreses',            descripcio: 'Cobraments, contractes, serveis defectuosos.' },
  salut:         { nom: 'Salut',                        descripcio: 'CAP, hospitals, llistes d\'espera, errors sanitaris.' },
  corrupcio:     { nom: 'Corrupció',                    descripcio: 'Contractació irregular, ús indegut de fons públics.' },
  delicte:       { nom: 'Delicte',                      descripcio: 'Agressions, robatoris, amenaces o estafes comunes.' },
  delicte_odi:   { nom: 'Delicte d\'odi',                descripcio: 'Agressió o discriminació per la identitat de la víctima (origen, llengua, orientació, gènere, religió...).' },
  dades:         { nom: 'Dades personals',              descripcio: 'Ús indegut de dades, filtracions, vigilància.' },
  llengua:       { nom: 'Drets lingüístics',            descripcio: 'Incompliments en matèria de català.' },
  catalanofobia: { nom: 'Catalanofòbia',                descripcio: 'Discriminació o delictes d\'odi per ser català.' },
  drets_humans:  { nom: 'Drets humans',                 descripcio: 'Abusos institucionals, drets civils, presons.' },
  habitatge:     { nom: 'Habitatge',                    descripcio: 'Desnonaments, accés, drets socials.' },
  medi_ambient:  { nom: 'Medi ambient',                 descripcio: 'Contaminació, urbanisme agressiu, espais naturals.' },
  laboral:       { nom: 'Drets laborals',               descripcio: 'Acomiadaments, assetjament, conveni, impagaments.' },
  transport:     { nom: 'Transport públic',             descripcio: 'Incidències, horaris, accessibilitat.' },
  ensenyament:   { nom: 'Ensenyament',                  descripcio: 'Drets educatius, ensenyament en català.' },
  racisme:       { nom: 'Racisme i xenofòbia',          descripcio: 'Discriminació per origen, color, religió.' },
  accessibilitat:{ nom: 'Accessibilitat digital',       descripcio: 'Webs i apps públiques no accessibles.' },
  lgtbi:         { nom: 'LGTBI-fòbia i drets',          descripcio: 'Discriminació o delictes d\'odi per orientació sexual, identitat o expressió de gènere.' },
  violencia_masclista: { nom: 'Violència masclista',    descripcio: 'Agressions, assetjament o discriminació per raó de sexe o gènere.' },
  qualsevol:     { nom: 'Qualsevol tema',               descripcio: 'Canals genèrics que poden tractar qualsevol assumpte (pressió mediàtica, etc).' },
};

const ENTITATS = [

  // ══════════════════════════════════════════
  //  ADMINISTRATIU
  // ══════════════════════════════════════════
  {
    id: 'sindic-greuges',
    nom: 'Síndic de Greuges de Catalunya',
    tipus: 'administratiu',
    ambit: 'Drets davant l\'administració',
    descripcio_breu: 'Defensa el ciutadà davant abusos o mal funcionament de l\'administració pública.',
    per_a_que: 'Fer que l\'administració es mogui quan no t\'ha respost, t\'ha tractat injustament, o un servei públic no funciona.',
    quan_usar: [
      'Un ajuntament o la Generalitat no et respon a un tràmit',
      'Tracte injust d\'una administració',
      'Un servei públic funciona malament',
      'Silenci administratiu',
    ],
    que_esperar: [
      'Obren una investigació del teu cas',
      'Fan recomanacions a l\'administració',
      'Seguiment institucional',
    ],
    punts_forts: ['Independent', 'Pressió formal efectiva', 'Gratuït'],
    limitacions: ['No pot sancionar', 'Procés lent', 'Les recomanacions no són obligatòries'],
    resultat_habitual: 'L\'administració revisa o rectifica el cas (no sempre).',
    temps: 'Setmanes / mesos',
    enllac: 'https://www.sindic.cat/ca/page.asp?id=65',
    pos:       [0.00, 0.00],
    pos_mobil: [0.00, 0.00],
  },
  {
    id: 'consum',
    nom: 'Agència Catalana del Consum',
    tipus: 'administratiu',
    ambit: 'Consumidors i empreses',
    descripcio_breu: 'Reclama davant empreses per serveis defectuosos, cobraments indeguts o contractes enganyosos.',
    per_a_que: 'Resoldre un conflicte amb una empresa o aconseguir que sigui sancionada per males pràctiques.',
    quan_usar: [
      'Cobraments indeguts',
      'Contractes enganyosos',
      'Productes o serveis defectuosos',
      'Telecos, llum, aigua, bancs...',
    ],
    que_esperar: [
      'Mediació amb l\'empresa',
      'Possible sanció administrativa',
    ],
    punts_forts: ['Molts casos es resolen', 'Via oficial reconeguda', 'Gratuït'],
    limitacions: ['Cal haver reclamat abans a l\'empresa', 'Lent'],
    resultat_habitual: 'Acord amb l\'empresa o resolució administrativa.',
    temps: 'Setmanes / mesos',
    enllac: 'https://consum.gencat.cat/ca/consultes-i-reclamacions/reclamacio-queixa-denuncia/',
    pos:       [0.333, 0.625],
    pos_mobil: [0.33, 0.40],
  },
  {
    id: 'catsalut',
    nom: 'Servei Català de la Salut',
    tipus: 'administratiu',
    ambit: 'Sanitat pública',
    descripcio_breu: 'Queixes sobre CAPs, hospitals, llistes d\'espera o errors sanitaris.',
    per_a_que: 'Fer arribar una queixa, reclamació o agraïment sobre l\'atenció sanitària rebuda.',
    quan_usar: [
      'Mala atenció al CAP o hospital',
      'Llistes d\'espera excessives',
      'Errors sanitaris o de gestió',
      'Problemes amb targeta sanitària',
    ],
    que_esperar: [
      'Resposta administrativa del centre o gerència',
      'Revisió del cas',
    ],
    punts_forts: ['Via oficial', 'Resposta formal'],
    limitacions: ['Ritme administratiu', 'No indemnitza directament'],
    resultat_habitual: 'Resposta del centre amb explicació o mesures correctores.',
    temps: 'Setmanes',
    enllac: 'https://ovt.gencat.cat/gsitfc/AppJava/generic/conqxsGeneric.do?webFormId=391&topicLevel1.id=1523&set-locale=ca_ES',
    pos:       [0.667, 0.125],
    pos_mobil: [0.67, 0.70],
  },
  {
    id: 'generalitat-instancia',
    nom: 'Generalitat — Instància genèrica',
    tipus: 'administratiu',
    ambit: 'Administració general',
    descripcio_breu: 'Canal universal quan no saps on dirigir-te dins l\'administració catalana.',
    per_a_que: 'Presentar una sol·licitud, queixa o suggeriment formal quan no hi ha un tràmit específic.',
    quan_usar: [
      'No saps a quin organisme correspon',
      'Sol·licituds genèriques',
      'Suggeriments o queixes internes',
    ],
    que_esperar: [
      'Derivació al departament competent',
      'Resposta formal (no sempre resolutiva)',
    ],
    punts_forts: ['Sempre disponible', 'Queda registrada oficialment'],
    limitacions: ['No resol directament', 'Pot tardar a arribar al destí correcte'],
    resultat_habitual: 'La sol·licitud es deriva i rebràs resposta del departament que correspongui.',
    temps: 'Setmanes',
    enllac: 'https://ovt.gencat.cat/gsitfc/AppJava/generic/conqxsGeneric.do?webFormId=31&topicLevel1.id=500&topicLevel2.id=624',
    pos:       [0.933, 0.375],
    pos_mobil: [0.83, 0.20],
  },

  // ══════════════════════════════════════════
  //  LEGAL
  // ══════════════════════════════════════════
  {
    id: 'antifrau',
    nom: 'Oficina Antifrau de Catalunya',
    tipus: 'legal',
    ambit: 'Corrupció i fons públics',
    descripcio_breu: 'Investiga corrupció, contractació irregular i ús indegut de recursos públics.',
    per_a_que: 'Posar en coneixement d\'un organisme independent sospites de corrupció o irregularitats a l\'administració.',
    quan_usar: [
      'Contractes públics sospitosos',
      'Ús irregular de diners públics',
      'Nepotisme o tracte de favor',
      'Conflictes d\'interès',
    ],
    que_esperar: [
      'Investigació confidencial',
      'Possible derivació a fiscalia',
      'Informes públics',
    ],
    punts_forts: ['Accepta denúncies anònimes', 'Independent', 'Alta capacitat d\'impacte'],
    limitacions: ['Cal certa base de proves', 'No tracta problemes personals petits'],
    resultat_habitual: 'Investigació interna i, si escau, trasllat al Ministeri Fiscal.',
    temps: 'Mesos',
    enllac: 'https://www.antifrau.cat/ca/investigacio/denuncieu.html',
    pos:       [0.20, 0.00],
    pos_mobil: [0.50, 0.10],
  },
  {
    id: 'mossos',
    nom: 'Mossos d\'Esquadra',
    tipus: 'legal',
    ambit: 'Delictes',
    descripcio_breu: 'Denúncia policial per delictes: robatoris, agressions, amenaces, delictes d\'odi.',
    per_a_que: 'Obrir via penal perquè un fet delictiu sigui investigat i, si escau, jutjat.',
    quan_usar: [
      'Robatoris, agressions físiques',
      'Amenaces, assetjament',
      'Delictes d\'odi o discriminació',
      'Violència masclista',
    ],
    que_esperar: [
      'Denúncia formal registrada',
      'Investigació policial',
      'Possible procés judicial',
    ],
    punts_forts: ['Imprescindible per delictes', 'Accés directe al sistema judicial'],
    limitacions: ['No resol conflictes administratius ni civils', 'Procés judicial pot ser llarg'],
    resultat_habitual: 'Atestat policial que passa al jutjat competent.',
    temps: 'Mesos / anys',
    enllac: 'https://ovt.gencat.cat/carpetaciutadana360/mfe-fc-app/gsitfc/AppJava/citpre/citpre.do?reqCode=simpleSearch&idTemaN2=29634',
    pos:       [0.533, 0.375],
    pos_mobil: [0.00, 0.30],
  },
  {
    id: 'apdcat',
    nom: 'Autoritat Catalana de Protecció de Dades',
    tipus: 'legal',
    ambit: 'Dades personals',
    descripcio_breu: 'Denúncia per ús indegut, filtracions o tractament abusiu de dades personals.',
    per_a_que: 'Fer que es sancioni una empresa o administració per vulnerar els teus drets de protecció de dades.',
    quan_usar: [
      'Filtracions de dades',
      'Ús de dades sense consentiment',
      'Videovigilància abusiva',
      'Spam o comunicacions no desitjades',
    ],
    que_esperar: [
      'Investigació formal',
      'Possibles sancions econòmiques',
    ],
    punts_forts: ['Molt efectiva', 'Pot imposar multes elevades'],
    limitacions: ['Només dades personals', 'Competència només sobre ens catalans'],
    resultat_habitual: 'Resolució amb sanció o advertiment al responsable.',
    temps: 'Mesos',
    enllac: 'https://www.apdcat.cat/ca/persones/reclama-i-denuncia',
    pos:       [0.067, 0.75],
    pos_mobil: [0.83, 0.50],
  },
  {
    id: 'jutjat-guardia',
    nom: 'Jutjat de Guàrdia — denúncia directa',
    tipus: 'legal',
    ambit: 'Via judicial penal',
    descripcio_breu: 'Presentar denúncia directament al jutjat sense passar per policia.',
    per_a_que: 'Iniciar un procés penal directament, útil quan vols controlar què es denuncia exactament.',
    quan_usar: [
      'Vols denunciar sense passar per Mossos',
      'Fets que requereixen actuació judicial urgent',
      'Delictes complexos on vols qualificació jurídica',
    ],
    que_esperar: [
      'Registre de la denúncia al jutjat',
      'Possible incoació de diligències',
    ],
    punts_forts: ['Més control sobre la redacció', 'Entrada directa al sistema judicial'],
    limitacions: ['Cal saber redactar-la bé (millor amb advocat)', 'No sempre accepten tots els casos'],
    resultat_habitual: 'Incoació de diligències prèvies o arxiu motivat.',
    temps: 'Mesos / anys',
    enllac: 'https://seujudicial.gencat.cat/ca/que_cal_fer/denuncia/',
    pos:       [0.867, 0.875],
    pos_mobil: [0.17, 0.80],
  },

  // ══════════════════════════════════════════
  //  LEGAL ESTRATÈGIC
  // ══════════════════════════════════════════
  {
    id: 'accio-cassandra',
    nom: 'Acció Cassandra',
    tipus: 'estrategic',
    ambit: 'Defensa de la nació catalana',
    descripcio_breu: 'Grup d\'advocats que porta casos judicials europeus en defensa de la minoria nacional catalana.',
    per_a_que: 'Impulsar procediments judicials (sovint europeus) per aconseguir el reconeixement jurídic de Catalunya com a nació minoritzada i perseguir delictes d\'odi contra catalans.',
    quan_usar: [
      'Delictes d\'odi contra persones per la seva condició de catalans',
      'Atacs al català com a llengua o al seu sistema educatiu',
      'Casos sobre el reconeixement jurídic d\'una nació minoritzada',
      'Vulneracions que requereixen via judicial internacional',
    ],
    que_esperar: [
      'Valoració legal del cas per part d\'advocats especialitzats',
      'Possible interposició de denúncies, querelles o procediments europeus',
      'Coordinació amb juristes d\'àmbit internacional',
    ],
    punts_forts: ['Focus en jurisdicció europea i drets de minories', 'Treball coordinat amb juristes internacionals', 'Voluntat de generar precedent jurídic'],
    limitacions: ['Casos seleccionats', 'Enfocats específicament en drets de la minoria nacional catalana', 'No és un canal massiu'],
    resultat_habitual: 'Procediments judicials amb voluntat de precedent i de reconeixement de drets.',
    temps: 'Mesos / anys',
    enllac: 'https://acciocassandra.cat/#denuncia',
    pos:       [0.20, 0.25],
    pos_mobil: [0.33, 0.20],
  },
  {
    id: 'iridia',
    nom: 'Irídia — Centre per la Defensa dels Drets Humans',
    tipus: 'estrategic',
    ambit: 'Drets humans',
    descripcio_breu: 'Defensa jurídica especialitzada en abusos policials i violència institucional.',
    per_a_que: 'Rebre assistència legal en casos de vulneració greu de drets humans per part d\'institucions.',
    quan_usar: [
      'Abusos policials',
      'Violència institucional',
      'Repressió de drets civils',
      'Casos amb component estructural',
    ],
    que_esperar: [
      'Assistència jurídica especialitzada',
      'Acompanyament al procés',
      'Litigis amb impacte',
    ],
    punts_forts: ['Alt impacte', 'Especialització reconeguda', 'Treball amb víctimes'],
    limitacions: ['Casos concrets i seleccionats', 'Recursos limitats'],
    resultat_habitual: 'Procediments judicials amb recorregut i incidència pública.',
    temps: 'Mesos / anys',
    enllac: 'https://iridia.cat/saidavi/',
    pos:       [0.467, 0.50],
    pos_mobil: [0.83, 0.80],
  },

  // ══════════════════════════════════════════
  //  PRESSIÓ SOCIAL
  // ══════════════════════════════════════════
  {
    id: 'plataforma-llengua',
    nom: 'Plataforma per la Llengua',
    tipus: 'social',
    ambit: 'Drets lingüístics',
    descripcio_breu: 'Defensa drets lingüístics davant empreses, administracions i situacions de discriminació.',
    per_a_que: 'Denunciar incompliments en matèria de català i fer que es moguin pressió política, mediàtica o legal.',
    quan_usar: [
      'Discriminació per parlar català',
      'Empreses que no respecten la llengua',
      'Administracions que no compleixen la normativa',
      'Incompliments a l\'etiquetatge, atenció al client...',
    ],
    que_esperar: [
      'Recollida i seguiment de la queixa',
      'Pressió pública o política',
      'Incidència (fins i tot internacional)',
    ],
    punts_forts: ['Molta incidència real', 'Aconsegueixen canvis normatius', 'Visibilitat'],
    limitacions: ['No resolen directament el cas individual', 'Depèn de volum de queixes'],
    resultat_habitual: 'Pressió sobre l\'empresa o administració i canvis progressius.',
    temps: 'Setmanes / mesos',
    enllac: 'https://www.queixes.plataforma-llengua.cat/',
    pos:       [0.00, 0.375],
    pos_mobil: [0.17, 0.50],
  },
  {
    id: 'omnium',
    nom: 'Òmnium Cultural',
    tipus: 'social',
    ambit: 'Drets civils i culturals',
    descripcio_breu: 'Defensa drets civils, culturals i col·lectius amb capacitat de mobilització.',
    per_a_que: 'Sumar-te o activar una causa col·lectiva que necessita mobilització i suport social.',
    quan_usar: [
      'Defensa de drets col·lectius',
      'Casos amb dimensió cultural o política',
      'Necessites mobilització social',
    ],
    que_esperar: [
      'Suport organitzatiu',
      'Campanyes públiques',
      'Pressió política',
    ],
    punts_forts: ['Gran base social', 'Capacitat mobilitzadora'],
    limitacions: ['No és un canal de queixa formal', 'Selecciona causes estratègiques'],
    resultat_habitual: 'Campanya pública o suport col·lectiu.',
    temps: 'Variable',
    enllac: 'https://www.omnium.cat/ca/contacte/',
    pos:       [0.60, 0.75],
    pos_mobil: [0.50, 0.70],
  },
  {
    id: 'facua',
    nom: 'FACUA Catalunya',
    tipus: 'social',
    ambit: 'Consumidors (contundent)',
    descripcio_breu: 'Defensa consumidors de forma més combativa: accions col·lectives i pressió mediàtica.',
    per_a_que: 'Sumar-te a accions col·lectives contra grans empreses o aconseguir visibilitat a un conflicte.',
    quan_usar: [
      'Conflictes amb grans empreses (telecos, bancs, elèctriques)',
      'Abusos que afecten molts consumidors',
      'Vols pressió mediàtica més enllà de la via administrativa',
    ],
    que_esperar: [
      'Assessorament si en ets soci/a',
      'Possible acció col·lectiva',
      'Pressió pública',
    ],
    punts_forts: ['Més contundent que Consum', 'Accions col·lectives'],
    limitacions: ['Serveis complets per a socis/es', 'No és institucional'],
    resultat_habitual: 'Denúncies públiques i, a vegades, sancions a empreses.',
    temps: 'Variable',
    enllac: 'https://facua.org/ca/cat/',
    pos:       [0.933, 0.00],
    pos_mobil: [0.83, 0.00],
  },

  // ══════════════════════════════════════════
  //  INCIDÈNCIA SECTORIAL
  // ══════════════════════════════════════════
  {
    id: 'observatori-desc',
    nom: 'Observatori DESC',
    tipus: 'sectorial',
    ambit: 'Habitatge i drets socials',
    descripcio_breu: 'Defensa drets econòmics, socials i culturals: habitatge, pobresa, desnonaments.',
    per_a_que: 'Rebre suport i incidència en vulneracions de drets socials amb component estructural.',
    quan_usar: [
      'Desnonaments',
      'Vulneració del dret a l\'habitatge',
      'Pobresa energètica',
      'Drets socials col·lectius',
    ],
    que_esperar: [
      'Incidència política i jurídica',
      'Suport en casos estructurals',
      'Informes i denúncia pública',
    ],
    punts_forts: ['Coneixement expert', 'Incidència institucional'],
    limitacions: ['No substitueix defensa jurídica individual'],
    resultat_habitual: 'Suport en casos col·lectius amb recorregut.',
    temps: 'Variable',
    enllac: 'https://observatoridesca.org/ca/contacte',
    pos:       [0.733, 0.50],
    pos_mobil: [0.67, 0.40],
  },
  // ══════════════════════════════════════════
  //  ADDICIONALS — AMB SEU ALS PAÏSOS CATALANS
  //  I WEB EN CATALÀ
  // ══════════════════════════════════════════
  {
    id: 'contenidor-rac1',
    nom: 'Contenidor — RAC1',
    tipus: 'social',
    ambit: 'Pressió mediàtica (consumidors)',
    descripcio_breu: 'Secció d\'El Món a RAC1 que recull queixes via WhatsApp, correu o telèfon i pressiona empreses en directe.',
    per_a_que: 'Enviar una queixa (preferiblement una nota de veu per WhatsApp al 669 10 10 10) i aconseguir que una empresa o administració reaccioni ràpid gràcies a la pressió mediàtica d\'un mitjà en català.',
    quan_usar: [
      'Empreses grans que no responen',
      'Conflictes repetits amb telecos, subministraments, transport…',
      'Casos amb possibilitat d\'impacte social',
    ],
    que_esperar: [
      'Possible emissió de la queixa al programa',
      'Reacció ràpida de l\'empresa implicada',
    ],
    punts_forts: ['Ràpid si la queixa és d\'interès', 'Format en català', 'Gran audiència'],
    limitacions: ['No totes les queixes s\'emeten', 'No és un canal oficial', 'També es pot contactar per correu (elmon@rac1.net) o telèfon 902 47 71 00'],
    resultat_habitual: 'L\'empresa contacta el ciutadà per resoldre el cas.',
    temps: 'Dies / setmanes',
    enllac: 'https://wa.me/34669101010',
    pos:       [0.40, 0.25],
    pos_mobil: [0.50, 0.30],
  },
  {
    id: 'sos-racisme',
    nom: 'SOS Racisme Catalunya',
    tipus: 'social',
    ambit: 'Racisme i xenofòbia',
    descripcio_breu: 'Denúncia i suport legal en casos de racisme, discriminació i delictes d\'odi.',
    per_a_que: 'Denunciar fets racistes, rebre suport jurídic i visibilitzar discriminacions estructurals.',
    quan_usar: [
      'Actes racistes o xenòfobs',
      'Discriminació per origen, color de pell o religió',
      'Abusos policials amb component racial',
      'Discurs d\'odi',
    ],
    que_esperar: [
      'Acompanyament jurídic del Servei d\'Atenció i Denúncia',
      'Inclusió del cas a l\'informe anual «Invisibles»',
      'Possible pressió pública',
    ],
    punts_forts: ['Especialització', 'Suport legal gratuït', 'Incidència estructural'],
    limitacions: ['Àmbit específic: racisme i xenofòbia'],
    resultat_habitual: 'Assessorament, denúncia si escau i inclusió a l\'informe de racisme a Catalunya.',
    temps: 'Setmanes',
    enllac: 'https://sosracisme.org/said/',
    pos:       [0.80, 0.625],
    pos_mobil: [0.00, 0.60],
  },
  {
    id: 'justicia-i-pau',
    nom: 'Justícia i Pau',
    tipus: 'social',
    ambit: 'Drets humans i pau',
    descripcio_breu: 'Entitat que defensa drets humans amb acompanyament jurídic i incidència política.',
    per_a_que: 'Rebre suport en vulneracions de drets humans, especialment en contextos penitenciaris, pau i persones migrants.',
    quan_usar: [
      'Vulneracions de drets humans',
      'Drets en context penitenciari',
      'Pau, no-violència i objecció',
      'Drets de persones migrants',
    ],
    que_esperar: [
      'Assessorament',
      'Acompanyament al procediment',
      'Incidència política i informes',
    ],
    punts_forts: ['Trajectòria llarga a Catalunya', 'Mirada integral de drets humans'],
    limitacions: ['No és un canal massiu de queixa formal'],
    resultat_habitual: 'Suport al cas i, si escau, denúncia pública o jurídica.',
    temps: 'Variable',
    enllac: 'https://www.justiciaipau.org/',
    pos:       [0.133, 0.50],
    pos_mobil: [0.83, 0.40],
  },
  {
    id: 'acpv',
    nom: 'Acció Cultural del País Valencià',
    tipus: 'social',
    ambit: 'Llengua i cultura catalanes al País Valencià',
    descripcio_breu: 'Entitat de referència per a la defensa del català i la cultura catalana al País Valencià.',
    per_a_que: 'Sumar-te o impulsar campanyes de defensa del català i dels drets lingüístics al País Valencià.',
    quan_usar: [
      'Incompliments en matèria de llengua al País Valencià',
      'Defensa de mitjans i ensenyament en català',
      'Activitats cíviques i culturals en català',
    ],
    que_esperar: [
      'Incidència política i cultural',
      'Campanyes i mobilitzacions',
    ],
    punts_forts: ['Trajectòria des de 1971', 'Gran base social al País Valencià', 'Web i activitat en català'],
    limitacions: ['No és un canal de queixa individual formal'],
    resultat_habitual: 'Pressió política, visibilitat i xarxa de suport.',
    temps: 'Variable',
    enllac: 'https://www.acpv.cat/contacte',
    pos:       [0.333, 0.375],
    pos_mobil: [0.33, 0.90],
  },
  {
    id: 'gepec',
    nom: 'GEPEC-EdC',
    tipus: 'sectorial',
    ambit: 'Medi ambient (ecosistemes catalans)',
    descripcio_breu: 'Grup d\'estudi i defensa d\'ecosistemes catalans amb capacitat de litigi i pressió territorial.',
    per_a_que: 'Denunciar impactes ambientals a Catalunya amb una entitat arrelada al territori i amb capacitat jurídica pròpia.',
    quan_usar: [
      'Contaminació industrial',
      'Projectes destructius al territori',
      'Afectacions a espais naturals de Catalunya',
      'Incompliments de normativa ambiental',
    ],
    que_esperar: [
      'Acompanyament tècnic',
      'Possibles accions legals',
      'Difusió pública',
    ],
    punts_forts: ['Arrel territorial (comarques de Tarragona)', 'Rigor tècnic', 'Capacitat jurídica'],
    limitacions: ['Focus a Catalunya', 'Recursos limitats'],
    resultat_habitual: 'Bloqueig o modificació de projectes, denúncia pública i administrativa.',
    temps: 'Mesos / anys',
    enllac: 'https://www.gepec.cat/',
    pos:       [0.80, 0.00],
    pos_mobil: [0.83, 0.60],
  },
  {
    id: 'politica-linguistica',
    nom: 'Direcció General de Política Lingüística',
    tipus: 'administratiu',
    ambit: 'Drets lingüístics (canal oficial)',
    descripcio_breu: 'Organisme de la Generalitat per a consultes, queixes i reclamacions sobre drets del català.',
    per_a_que: 'Fer arribar a la Generalitat una queixa o consulta oficial en matèria de llengua catalana.',
    quan_usar: [
      'Administracions o serveis públics que no respecten el català',
      'Incompliments normatius en matèria lingüística',
      'Dubtes sobre drets lingüístics',
    ],
    que_esperar: [
      'Resposta oficial de la Generalitat',
      'Derivació a l\'òrgan competent si escau',
    ],
    punts_forts: ['Canal oficial', 'Obligació de resposta administrativa'],
    limitacions: ['Competència limitada a Catalunya', 'No sanciona directament empreses privades'],
    resultat_habitual: 'Resposta administrativa, gestió interna o derivació.',
    temps: 'Setmanes',
    enllac: 'https://ovt.gencat.cat/gsitfc/AppJava/generic/conqxsGeneric.do?webFormId=11&set-locale=ca_ES',
    pos:       [0.20, 0.75],
    pos_mobil: [0.67, 0.10],
  },
  {
    id: 'accio-pel-catala',
    nom: 'Acció pel Català — Bot de queixes',
    tipus: 'social',
    ambit: 'Drets lingüístics (eina automatitzada)',
    descripcio_breu: 'Bot que automatitza la redacció i l\'enviament de queixes per incompliments en matèria de llengua catalana.',
    per_a_que: 'Enviar ràpidament queixes formals a empreses i administracions que no respecten el català, amb el text generat automàticament pel bot.',
    quan_usar: [
      'Empreses que no atenen en català',
      'Cartes, factures o etiquetatge sense català',
      'Serveis digitals que no ofereixen català',
      'Vols enviar queixes sense perdre temps redactant-les',
    ],
    que_esperar: [
      'El bot genera i envia la queixa',
      'Pressió acumulada amb altres queixes similars',
    ],
    punts_forts: ['Molt ràpid', 'Zero fricció per a l\'usuari', 'Web i servei en català'],
    limitacions: ['No és un canal oficial', 'Depèn que l\'empresa respongui'],
    resultat_habitual: 'Queixa enviada a l\'empresa; pressió acumulada amb la resta de queixes rebudes.',
    temps: 'Minuts',
    enllac: 'https://acciopelcatala.cat/bot-de-queixes/',
    pos:       [0.733, 0.25],
    pos_mobil: [0.00, 0.80],
  },
  {
    id: 'intersindical',
    nom: 'La Intersindical — Catalunya',
    tipus: 'social',
    ambit: 'Drets laborals (sindicat)',
    descripcio_breu: 'Sindicat català de classe per defensar els drets laborals i acompanyar en conflictes amb l\'empresa.',
    per_a_que: 'Rebre assessorament i suport sindical en conflictes laborals (acomiadaments, assetjament, impagaments, incompliments conveni...).',
    quan_usar: [
      'Acomiadament improcedent o nul',
      'Assetjament laboral o mobbing',
      'Incompliments del conveni col·lectiu',
      'Impagaments de salari o hores',
      'Necessites representació a l\'empresa',
    ],
    que_esperar: [
      'Assessorament sindical i jurídic',
      'Acompanyament al procés',
      'Possible via judicial via l\'assessoria laboral',
    ],
    punts_forts: ['Arrelament al territori', 'Sindicat en català', 'Combina defensa jurídica i pressió col·lectiva'],
    limitacions: ['Serveis complets sovint per afiliats'],
    resultat_habitual: 'Mediació, denúncia formal o judicialització del conflicte laboral.',
    temps: 'Setmanes / mesos',
    enllac: 'https://laintersindical.cat/contacte/',
    pos:       [0.20, 0.625],
    pos_mobil: [0.67, 0.60],
  },
  {
    id: 'adenc',
    nom: 'ADENC — Associació per a la Defensa i Estudi de la Natura',
    tipus: 'sectorial',
    ambit: 'Medi ambient (Vallès Occidental i Catalunya Central)',
    descripcio_breu: 'Entitat ecologista amb arrel al Vallès que denuncia afectacions ambientals i defensa espais naturals.',
    per_a_que: 'Denunciar impactes ambientals al Vallès i territoris propers amb una entitat arrelada i amb trajectòria en litigi ambiental.',
    quan_usar: [
      'Urbanisme agressiu o projectes destructius al Vallès',
      'Afectacions a espais naturals (rius, boscos, connectors)',
      'Incompliments de normativa ambiental',
      'Impactes d\'infraestructures al territori',
    ],
    que_esperar: [
      'Acompanyament tècnic',
      'Possibles accions legals',
      'Difusió pública',
    ],
    punts_forts: ['Arrelament territorial', 'Trajectòria llarga', 'Web i activitat en català'],
    limitacions: ['Focus geogràfic a Vallès i comarques veïnes'],
    resultat_habitual: 'Pressió, denúncia pública o accions administratives/judicials.',
    temps: 'Mesos / anys',
    enllac: 'https://adenc.cat/',
    pos:       [0.40, 0.625],
    pos_mobil: [0.17, 0.70],
  },
  // ══════════════════════════════════════════
  //  HABITATGE
  // ══════════════════════════════════════════
  {
    id: 'sindicat-llogateres',
    nom: 'Sindicat de Llogateres',
    tipus: 'social',
    ambit: 'Drets de lloguer i habitatge',
    descripcio_breu: 'Sindicat que defensa drets de llogateres davant pujades abusives, assetjament i desnonaments.',
    per_a_que: 'Rebre assessorament col·lectiu i acompanyament davant abusos del teu propietari o gran tenidor.',
    quan_usar: [
      'Pujades de lloguer abusives',
      'Assetjament immobiliari (mobbing)',
      'No renovació contra la llei',
      'Desnonaments',
    ],
    que_esperar: [
      'Assessorament legal col·lectiu',
      'Acció col·lectiva si escau',
      'Pressió pública i política',
    ],
    punts_forts: ['Força col·lectiva', 'Experiència en litigis d\'habitatge', 'Campanyes d\'impacte'],
    limitacions: ['Prioritzen casos estratègics i col·lectius'],
    resultat_habitual: 'Reducció de lloguer, aturada de desnonament o acció col·lectiva.',
    temps: 'Setmanes / mesos',
    enllac: 'https://sindicatdellogateres.org/recurs/',
    pos:       [0.333, 0.50],
    pos_mobil: [0.00, 0.50],
  },
  {
    id: 'entrebarris',
    nom: 'EntreBarris',
    tipus: 'social',
    ambit: 'Habitatge i drets veïnals',
    descripcio_breu: 'Xarxa de suport veïnal i mutualisme en habitatge i drets socials.',
    per_a_que: 'Sumar-te a una xarxa de suport veïnal en casos d\'habitatge i vulnerabilitat, amb suport entre iguals.',
    quan_usar: [
      'Problemes d\'habitatge al teu barri',
      'Suport veïnal davant desnonaments',
      'Accions d\'organització comunitària',
    ],
    que_esperar: [
      'Suport mutu i organització comunitària',
      'Acompanyament als casos',
    ],
    punts_forts: ['Arrelament de barri', 'Xarxa de suport mutualista'],
    limitacions: ['No és canal formal de queixa'],
    resultat_habitual: 'Suport al cas i acció col·lectiva.',
    temps: 'Variable',
    enllac: 'https://entrebarris.org/contacte/',
    pos:       [0.60, 0.00],
    pos_mobil: [0.67, 0.50],
  },

  // ══════════════════════════════════════════
  //  VIOLÈNCIA MASCLISTA
  // ══════════════════════════════════════════
  {
    id: 'institut-catala-dones',
    nom: 'Institut Català de les Dones',
    tipus: 'administratiu',
    ambit: 'Violència masclista (canal oficial)',
    descripcio_breu: 'Organisme de la Generalitat de Catalunya per a l\'atenció a dones víctimes de violència masclista.',
    per_a_que: 'Rebre atenció, recursos i acompanyament de l\'administració pública catalana en casos de violència masclista.',
    quan_usar: [
      'Violència masclista a la parella o exparella',
      'Assetjament sexual o laboral per raó de gènere',
      'Necessites recursos d\'acollida o suport',
    ],
    que_esperar: [
      'Atenció especialitzada',
      'Derivació a recursos (acollida, jurídic, psicològic)',
    ],
    punts_forts: ['Canal oficial', 'Xarxa de recursos pública'],
    limitacions: ['Específicament dones víctimes de violència masclista'],
    resultat_habitual: 'Atenció i activació de recursos segons el cas.',
    temps: 'Dies / setmanes',
    enllac: 'https://dones.gencat.cat/ca/ambits/atencio-a-les-dones/',
    pos:       [0.80, 0.75],
    pos_mobil: [0.83, 0.10],
  },
  {
    id: 'helia',
    nom: 'Associació Hèlia',
    tipus: 'social',
    ambit: 'Violència masclista (acompanyament)',
    descripcio_breu: 'Associació que acompanya dones víctimes de violència masclista amb suport integral.',
    per_a_que: 'Rebre acompanyament integral (jurídic, psicològic, social) davant violència masclista.',
    quan_usar: [
      'Violència a la parella',
      'Necessites suport emocional i jurídic',
      'Vols un acompanyament més enllà de la via oficial',
    ],
    que_esperar: [
      'Acompanyament personalitzat',
      'Atenció jurídica i psicològica',
      'Xarxa de suport',
    ],
    punts_forts: ['Mirada integral', 'Trajectòria', 'Suport a llarg termini'],
    limitacions: ['Àmbit específic: dones víctimes de violència masclista'],
    resultat_habitual: 'Acompanyament i recuperació al llarg del procés.',
    temps: 'Mesos',
    enllac: 'https://heliadones.org/contacte/',
    pos:       [0.267, 0.625],
    pos_mobil: [0.50, 0.50],
  },
  {
    id: 'fundacio-surt',
    nom: 'Fundació Surt',
    tipus: 'social',
    ambit: 'Drets de les dones (inclusió i violència)',
    descripcio_breu: 'Fundació dedicada a la defensa dels drets de les dones, la inclusió i la violència masclista.',
    per_a_que: 'Rebre suport integral (laboral, formatiu, jurídic) davant situacions de vulnerabilitat o violència masclista.',
    quan_usar: [
      'Violència masclista',
      'Situacions de vulnerabilitat laboral o econòmica',
      'Necessites suport en inclusió i ocupació',
    ],
    que_esperar: [
      'Acompanyament',
      'Programes d\'inclusió laboral',
      'Suport jurídic i psicològic',
    ],
    punts_forts: ['Mirada integral', 'Programes diversos', 'Trajectòria llarga'],
    limitacions: ['Àmbit dones i col·lectius vulnerabilitzats'],
    resultat_habitual: 'Acompanyament i activació de recursos segons el cas.',
    temps: 'Mesos',
    enllac: 'https://surt.org/contacte-surt/',
    pos:       [0.467, 0.75],
    pos_mobil: [0.17, 0.60],
  },

  // ══════════════════════════════════════════
  //  DRETS LGTBI+
  // ══════════════════════════════════════════
  {
    id: 'observatori-homofobia',
    nom: 'Observatori Contra l\'Homofòbia',
    tipus: 'social',
    ambit: 'Drets LGTBI+ (denúncia i suport)',
    descripcio_breu: 'Recull i acompanya denúncies de LGTBI-fòbia a Catalunya, amb assistència jurídica i informes.',
    per_a_que: 'Denunciar incidents d\'odi o discriminació per orientació sexual, identitat o expressió de gènere, i rebre suport jurídic i emocional.',
    quan_usar: [
      'Agressions físiques o verbals LGTBI-fòbiques',
      'Discriminació al treball, habitatge o serveis',
      'Discurs d\'odi a internet o a l\'espai públic',
    ],
    que_esperar: [
      'Recull oficial del cas',
      'Acompanyament jurídic',
      'Inclusió a l\'informe anual',
    ],
    punts_forts: ['Especialització', 'Suport legal', 'Incidència pública'],
    limitacions: ['Àmbit específic: LGTBI-fòbia'],
    resultat_habitual: 'Assessorament, denúncia si escau, i visibilitat al cas.',
    temps: 'Setmanes',
    enllac: 'https://lobservatori.cat/ca/inici/denuncia/',
    pos:       [0.867, 0.50],
    pos_mobil: [0.83, 0.40],
  },
  {
    id: 'casal-lambda',
    nom: 'Casal Lambda',
    tipus: 'social',
    ambit: 'Drets LGTBI+ (assessoria jurídica)',
    descripcio_breu: 'Entitat LGTBI+ referent a Catalunya; ofereix assessoria jurídica especialitzada.',
    per_a_que: 'Rebre assessorament jurídic especialitzat en casos de discriminació o drets LGTBI+ a Catalunya.',
    quan_usar: [
      'Dubtes legals sobre drets LGTBI+',
      'Discriminació laboral, escolar o familiar',
      'Situacions d\'assetjament',
    ],
    que_esperar: [
      'Assessorament jurídic gratuït o a preu reduït',
      'Derivació a altres serveis si cal',
    ],
    punts_forts: ['Trajectòria llarga', 'Especialització jurídica'],
    limitacions: ['Focus a Catalunya'],
    resultat_habitual: 'Orientació legal i suport al cas.',
    temps: 'Setmanes',
    enllac: 'https://lambda.cat/assessoriajuridica/',
    pos:       [0.067, 0.00],
    pos_mobil: [0.50, 0.20],
  },
  {
    id: 'fundacio-enllac',
    nom: 'Fundació Enllaç',
    tipus: 'social',
    ambit: 'Drets LGTBI+ (acompanyament i grans)',
    descripcio_breu: 'Acompanyament a persones LGTBI+ grans i en situació de vulnerabilitat.',
    per_a_que: 'Rebre suport si ets persona LGTBI+ en situació de vulnerabilitat, especialment si ets gran, davant discriminació o aïllament.',
    quan_usar: [
      'Discriminació a residències o serveis socials',
      'Acompanyament davant vulnerabilitat',
      'Suport emocional i jurídic',
    ],
    que_esperar: [
      'Acompanyament personalitzat',
      'Recursos i derivacions',
    ],
    punts_forts: ['Focus en col·lectius vulnerables', 'Mirada intergeneracional'],
    limitacions: ['Àmbit específic'],
    resultat_habitual: 'Suport i derivació a recursos adequats.',
    temps: 'Variable',
    enllac: 'https://fundacioenllac.cat/contacte/',
    pos:       [0.60, 0.875],
    pos_mobil: [0.17, 0.90],
  },
  {
    id: 'acathi',
    nom: 'ACATHI',
    tipus: 'social',
    ambit: 'Drets LGTBI+ migrants i refugiats',
    descripcio_breu: 'Defensa i acompanyament de persones LGTBI+ migrants i refugiades.',
    per_a_que: 'Rebre suport si ets persona LGTBI+ migrada o refugiada i necessites acompanyament jurídic o social.',
    quan_usar: [
      'Sol·licituds d\'asil per motius LGTBI+',
      'Discriminació interseccional',
      'Necessites acompanyament especialitzat',
    ],
    que_esperar: [
      'Acompanyament jurídic i social',
      'Derivació a recursos',
    ],
    punts_forts: ['Especialització interseccional', 'Xarxa internacional'],
    limitacions: ['Àmbit específic: LGTBI+ migrant'],
    resultat_habitual: 'Suport legal i social al cas.',
    temps: 'Mesos',
    enllac: 'https://acathi.org/',
    pos:       [0.40, 0.00],
    pos_mobil: [0.67, 0.80],
  },
  {
    id: 'lambda-valencia',
    nom: 'Lambda València',
    tipus: 'social',
    ambit: 'Drets LGTBI+ (País Valencià)',
    descripcio_breu: 'Entitat LGTBI+ referent al País Valencià; suport i denúncia de discriminació.',
    per_a_que: 'Denunciar o rebre suport davant discriminació LGTBI+ al País Valencià.',
    quan_usar: [
      'Discriminació al PV per orientació sexual o identitat',
      'Assetjament o delictes d\'odi',
      'Acompanyament jurídic i emocional',
    ],
    que_esperar: [
      'Acompanyament i assessorament',
      'Denúncia si escau',
    ],
    punts_forts: ['Referent al PV', 'Trajectòria llarga'],
    limitacions: ['Focus PV'],
    resultat_habitual: 'Orientació, acompanyament i denúncia.',
    temps: 'Setmanes',
    enllac: 'https://lambdavalencia.org/contacte/',
    pos:       [0.20, 0.125],
    pos_mobil: [0.00, 0.80],
  },

  // ══════════════════════════════════════════
  //  ECOLOGISTES / DEFENSA DEL TERRITORI
  //  (Catalunya / PV / Illes Balears)
  // ══════════════════════════════════════════
  {
    id: 'depana',
    nom: 'DEPANA — Lliga per a la Defensa del Patrimoni Natural',
    tipus: 'sectorial',
    ambit: 'Biodiversitat i espais naturals (Catalunya)',
    descripcio_breu: 'Entitat històrica catalana centrada en biodiversitat i defensa d\'espais protegits.',
    per_a_que: 'Denunciar impactes sobre la biodiversitat i espais naturals a Catalunya amb una entitat amb trajectòria i capacitat tècnica.',
    quan_usar: [
      'Afectacions a espais protegits',
      'Pèrdua de biodiversitat',
      'Projectes que amenacen hàbitats',
    ],
    que_esperar: ['Acompanyament tècnic', 'Campanyes i incidència', 'Possibles accions legals'],
    punts_forts: ['Trajectòria llarga (des de 1976)', 'Coneixement tècnic', 'Xarxa d\'entitats'],
    limitacions: ['Prioritzen casos d\'interès col·lectiu'],
    resultat_habitual: 'Pressió, denúncia pública i/o accions administratives.',
    temps: 'Mesos / anys',
    enllac: 'https://depana.org/',
    pos:       [0.933, 0.50],
    pos_mobil: [0.83, 0.40],
  },
  {
    id: 'iaeden',
    nom: 'IAEDEN — Institució Alt-empordanesa per a la Defensa de la Natura',
    tipus: 'sectorial',
    ambit: 'Defensa territorial (Alt Empordà)',
    descripcio_breu: 'Referent ambiental a les comarques gironines, molt activa en defensa territorial i litoral.',
    per_a_que: 'Denunciar impactes territorials a les comarques gironines amb una entitat arrelada i amb experiència.',
    quan_usar: [
      'Urbanisme agressiu a l\'Empordà',
      'Impactes a espais naturals gironins',
      'Incompliments de normativa ambiental',
    ],
    que_esperar: ['Acompanyament tècnic', 'Possibles accions legals', 'Campanyes'],
    punts_forts: ['Arrelament territorial', 'Experiència en litigi ambiental'],
    limitacions: ['Focus a Girona/Alt Empordà'],
    resultat_habitual: 'Bloqueig o modificació de projectes, denúncia pública.',
    temps: 'Mesos / anys',
    enllac: 'https://iaeden.cat/',
    pos:       [0.067, 0.125],
    pos_mobil: [0.17, 0.50],
  },
  {
    id: 'plataforma-ebre',
    nom: 'Plataforma en Defensa de l\'Ebre',
    tipus: 'sectorial',
    ambit: 'Riu Ebre i delta',
    descripcio_breu: 'Defensa del riu Ebre, el delta i les terres riberenques davant transvasaments i impactes.',
    per_a_que: 'Sumar-te a la defensa de l\'Ebre i les Terres de l\'Ebre davant impactes hídrics o territorials.',
    quan_usar: [
      'Transvasaments i gestió de l\'aigua',
      'Projectes que afecten el delta',
      'Extracció d\'àrids o contaminació',
    ],
    que_esperar: ['Campanyes públiques', 'Incidència política', 'Accions col·lectives'],
    punts_forts: ['Moviment popular consolidat', 'Gran capacitat de mobilització'],
    limitacions: ['No és canal de queixa individual'],
    resultat_habitual: 'Pressió política i mobilització ciutadana.',
    temps: 'Variable',
    enllac: 'https://www.ebre.net/bloc/',
    pos:       [0.533, 0.875],
    pos_mobil: [0.67, 0.30],
  },
  {
    id: 'sos-costa-brava',
    nom: 'SOS Costa Brava',
    tipus: 'sectorial',
    ambit: 'Defensa del litoral (Costa Brava)',
    descripcio_breu: 'Plataforma contra la urbanització del litoral i la sobreexplotació de la Costa Brava.',
    per_a_que: 'Denunciar projectes urbanístics o turístics que amenacen el litoral gironí.',
    quan_usar: [
      'Nous projectes urbanístics a la Costa Brava',
      'Ampliacions turístiques',
      'Ocupació d\'espais naturals',
    ],
    que_esperar: ['Campanyes', 'Accions legals', 'Difusió pública'],
    punts_forts: ['Focus clar', 'Capacitat legal i mediàtica', 'Casos d\'èxit'],
    limitacions: ['Àmbit geogràfic concret'],
    resultat_habitual: 'Bloqueig o modificació de projectes.',
    temps: 'Mesos / anys',
    enllac: 'https://soscostabrava.cat/',
    pos:       [0.333, 0.875],
    pos_mobil: [0.50, 0.50],
  },
  {
    id: 'no-a-la-mat',
    nom: 'No a la MAT',
    tipus: 'sectorial',
    ambit: 'Infraestructures elèctriques (línies MAT)',
    descripcio_breu: 'Plataforma contra la instal·lació de grans línies elèctriques d\'alta tensió.',
    per_a_que: 'Sumar-te a la defensa territorial davant macroprojectes de línies MAT i les seves afectacions.',
    quan_usar: [
      'Nous traçats de línies MAT',
      'Ampliacions d\'infraestructures elèctriques',
      'Impactes a pagesia i paisatge',
    ],
    que_esperar: ['Campanyes', 'Accions col·lectives', 'Incidència política'],
    punts_forts: ['Moviment territorial consolidat', 'Experiència jurídica'],
    limitacions: ['Focus en línies elèctriques'],
    resultat_habitual: 'Pressió política, a vegades modificació o aturada de projectes.',
    temps: 'Mesos / anys',
    enllac: 'https://noalamatselva.cat/',
    pos:       [0.667, 0.25],
    pos_mobil: [0.00, 0.20],
  },
  {
    id: 'xuquer-viu',
    nom: 'Xúquer Viu',
    tipus: 'sectorial',
    ambit: 'Riu Xúquer i gestió de l\'aigua (PV)',
    descripcio_breu: 'Defensa del riu Xúquer, la seva conca i la gestió sostenible de l\'aigua al País Valencià.',
    per_a_que: 'Denunciar impactes a la conca del Xúquer o sumar-te a campanyes d\'aigua al PV.',
    quan_usar: [
      'Transvasaments',
      'Contaminació del riu',
      'Afectacions a la conca',
    ],
    que_esperar: ['Campanyes', 'Accions col·lectives', 'Incidència'],
    punts_forts: ['Focus territorial', 'Coneixement específic'],
    limitacions: ['Àmbit concret (Xúquer)'],
    resultat_habitual: 'Pressió política i mobilització.',
    temps: 'Variable',
    enllac: 'https://xuquerviu.net/contacta/',
    pos:       [0.867, 0.25],
    pos_mobil: [0.33, 0.50],
  },
  {
    id: 'per-l-horta',
    nom: 'Per l\'Horta',
    tipus: 'sectorial',
    ambit: 'Horta de València (defensa urbana)',
    descripcio_breu: 'Defensa de l\'Horta de València davant l\'especulació urbanística i la pèrdua d\'espai agrari.',
    per_a_que: 'Sumar-te a la defensa de l\'Horta davant projectes urbanístics o viaris que l\'amenacen.',
    quan_usar: [
      'Noves infraestructures que afecten l\'Horta',
      'Pèrdua d\'espais agraris',
      'Especulació urbanística a l\'àrea metropolitana de València',
    ],
    que_esperar: ['Campanyes', 'Accions col·lectives'],
    punts_forts: ['Moviment consolidat', 'Arrelament local'],
    limitacions: ['Àmbit Horta de València'],
    resultat_habitual: 'Pressió política i mobilització.',
    temps: 'Variable',
    enllac: 'https://perlhorta.info/',
    pos:       [0.267, 0.375],
    pos_mobil: [0.33, 0.80],
  },
  {
    id: 'amics-terra',
    nom: 'Amics de la Terra Mallorca',
    tipus: 'sectorial',
    ambit: 'Sostenibilitat i canvi climàtic (IB)',
    descripcio_breu: 'Sostenibilitat, residus i canvi climàtic a les Illes Balears.',
    per_a_que: 'Denunciar impactes climàtics o de residus a les Illes amb una entitat amb trajectòria internacional.',
    quan_usar: [
      'Gestió de residus',
      'Impactes climàtics',
      'Energia i mobilitat',
    ],
    que_esperar: ['Campanyes', 'Informes tècnics', 'Incidència'],
    punts_forts: ['Xarxa internacional', 'Especialització tècnica'],
    limitacions: ['Prioritzen temes estratègics'],
    resultat_habitual: 'Pressió política, publicacions, campanyes.',
    temps: 'Variable',
    enllac: 'https://www.amicsdelaterra.org/',
    pos:       [0.467, 0.125],
    pos_mobil: [0.17, 0.80],
  },
  {
    id: 'terraferida',
    nom: 'Terraferida',
    tipus: 'sectorial',
    ambit: 'Massificació turística (IB)',
    descripcio_breu: 'Denúncia de la massificació turística i urbanística a Mallorca i Illes Balears.',
    per_a_que: 'Sumar-te o denunciar impactes de la massificació turística i urbanística a les Illes.',
    quan_usar: [
      'Nous grans projectes turístics',
      'Urbanisme agressiu a IB',
      'Pressió sobre recursos (aigua, sòl)',
    ],
    que_esperar: ['Campanyes', 'Difusió pública', 'Dades i informes'],
    punts_forts: ['Focus clar', 'Gran capacitat mediàtica'],
    limitacions: ['Enfocat a Balears'],
    resultat_habitual: 'Pressió mediàtica i política.',
    temps: 'Variable',
    enllac: 'https://terraferida.cat/contacta/',
    pos:       [0.133, 0.125],
    pos_mobil: [0.50, 0.10],
  },
  {
    id: 'salvem-sa-badia',
    nom: 'Salvem Sa Badia de Portmany',
    tipus: 'sectorial',
    ambit: 'Litoral i ecosistemes marins (Eivissa)',
    descripcio_breu: 'Defensa del litoral i els ecosistemes marins de Sa Badia de Portmany (Eivissa).',
    per_a_que: 'Sumar-te a la defensa del litoral d\'Eivissa davant impactes nàutics, ancoratges o projectes.',
    quan_usar: [
      'Projectes que afecten Sa Badia de Portmany',
      'Ancoratges sobre posidònia',
      'Contaminació marina',
    ],
    que_esperar: ['Campanyes', 'Accions col·lectives'],
    punts_forts: ['Arrelament local', 'Focus clar'],
    limitacions: ['Àmbit geogràfic molt concret'],
    resultat_habitual: 'Pressió política i mobilització.',
    temps: 'Variable',
    enllac: 'https://www.salvemsabadia.com/',
    pos:       [0.733, 0.875],
    pos_mobil: [0.83, 0.80],
  },
  {
    id: 'oac-ajuntaments',
    nom: 'OAC — Oficines d\'Atenció Ciutadana',
    tipus: 'administratiu',
    ambit: 'Ajuntaments (tràmits i queixes locals)',
    descripcio_breu: 'Canal oficial del teu ajuntament per tràmits, queixes i suggeriments locals. Cada municipi té la seva.',
    per_a_que: 'Fer arribar al teu ajuntament una queixa, suggeriment o tràmit sobre serveis i afers municipals.',
    quan_usar: [
      'Espai públic: soroll, neteja, enllumenat, mobiliari...',
      'Serveis municipals (escoles bressol, esports, biblioteques...)',
      'Tributs i taxes locals',
      'Tràmits amb l\'ajuntament',
    ],
    que_esperar: [
      'Registre oficial de la sol·licitud',
      'Resposta administrativa del servei competent',
    ],
    punts_forts: ['Primer punt de contacte amb el municipi', 'Obligació de resposta administrativa'],
    limitacions: ['Només competències municipals', 'Cal conèixer el teu ajuntament'],
    resultat_habitual: 'Derivació al servei municipal corresponent i resposta formal.',
    temps: 'Setmanes',
    enllac: 'https://web.gencat.cat/ca/atenem/oficines-atencio-ciutadana',
    pos:       [0.467, 0.875],
    pos_mobil: [0.50, 0.60],
  },

  // ══════════════════════════════════════════
  //  ILLES BALEARS
  // ══════════════════════════════════════════
  {
    id: 'sindic-ib',
    nom: 'Atenció a la Ciutadania — Govern de les Illes Balears',
    tipus: 'administratiu',
    ambit: 'Drets davant l\'administració (IB)',
    descripcio_breu: 'Canal oficial del Govern Balear per a queixes i suggeriments. El Síndic de Greuges IB mai s\'ha posat en marxa; aquesta és la via vigent.',
    per_a_que: 'Fer arribar una queixa, suggeriment o consulta al Govern de les Illes Balears quan no et responen o actuen malament.',
    quan_usar: [
      'Silenci administratiu del Govern Balear o ajuntaments IB',
      'Serveis públics insulars que funcionen malament',
      'Tracte injust d\'una administració balear',
    ],
    que_esperar: [
      'Registre oficial de la queixa',
      'Resposta administrativa del servei competent',
    ],
    punts_forts: ['Canal oficial operatiu', 'Obligació de resposta'],
    limitacions: ['No és un defensor independent com un síndic', 'La Sindicatura de Greuges IB mai s\'ha arribat a constituir'],
    resultat_habitual: 'Resposta administrativa o derivació al servei competent. Per a casos greus cal recórrer al Defensor del Pueblo.',
    temps: 'Setmanes',
    enllac: 'https://www.caib.es/sites/queixesisuggeriments/ca/queixes_telematica/',
    pos:       [0.533, 0.125],
    pos_mobil: [0.67, 0.30],
  },
  {
    id: 'ocb',
    nom: 'Obra Cultural Balear (OCB)',
    tipus: 'social',
    ambit: 'Llengua i cultura catalanes (IB)',
    descripcio_breu: 'Entitat de referència per a la defensa de la llengua i la cultura catalanes a les Illes Balears.',
    per_a_que: 'Impulsar campanyes i donar suport en matèria de llengua i cultura catalanes a les Balears.',
    quan_usar: [
      'Incompliments normatius en matèria de català a IB',
      'Defensa de l\'ensenyament en català',
      'Drets lingüístics al dia a dia',
    ],
    que_esperar: [
      'Acompanyament i incidència política',
      'Campanyes públiques',
    ],
    punts_forts: ['Gran base social a les Illes', 'Trajectòria llarga'],
    limitacions: ['No és un canal formal de queixa'],
    resultat_habitual: 'Pressió i xarxa de suport.',
    temps: 'Variable',
    enllac: 'https://ocb.cat/contacte/',
    pos:       [0.667, 0.625],
    pos_mobil: [0.67, 0.80],
  },
  {
    id: 'gob',
    nom: 'GOB — Grup Balear d\'Ornitologia',
    tipus: 'sectorial',
    ambit: 'Medi ambient (Illes Balears)',
    descripcio_breu: 'Grup ecologista referent a les Illes, amb capacitat de litigi i incidència territorial.',
    per_a_que: 'Denunciar impactes ambientals a les Illes Balears amb una entitat arrelada amb capacitat jurídica.',
    quan_usar: [
      'Urbanisme agressiu a les Illes',
      'Impactes a espais naturals balears',
      'Incompliments de normativa ambiental',
    ],
    que_esperar: [
      'Acompanyament tècnic',
      'Possibles accions legals',
      'Difusió pública',
    ],
    punts_forts: ['Arrelament territorial', 'Capacitat jurídica', 'Trajectòria'],
    limitacions: ['Focus Illes Balears'],
    resultat_habitual: 'Bloqueig o modificació de projectes, denúncia pública.',
    temps: 'Mesos / anys',
    enllac: 'https://www.gobmallorca.com/denuncia/',
    pos:       [0.133, 0.875],
    pos_mobil: [0.17, 0.20],
  },

  // ══════════════════════════════════════════
  //  PAÍS VALENCIÀ
  // ══════════════════════════════════════════
  {
    id: 'sindic-cv',
    nom: 'Síndic de Greuges de la Comunitat Valenciana',
    tipus: 'administratiu',
    ambit: 'Drets davant l\'administració (PV)',
    descripcio_breu: 'Defensor del ciutadà davant les administracions del País Valencià.',
    per_a_que: 'Reclamar davant la Generalitat Valenciana o els ajuntaments del País Valencià.',
    quan_usar: [
      'Silenci administratiu al PV',
      'Serveis públics valencians mal gestionats',
      'Tracte injust d\'una administració valenciana',
    ],
    que_esperar: [
      'Investigació del cas',
      'Recomanacions a l\'administració',
    ],
    punts_forts: ['Independent', 'Cobertura específica del PV'],
    limitacions: ['No pot sancionar'],
    resultat_habitual: 'Revisió o rectificació administrativa (no sempre).',
    temps: 'Setmanes / mesos',
    enllac: 'https://www.elsindic.com/te-ayudamos/presentar-una-queja-consulta/',
    pos:       [0.867, 0.125],
    pos_mobil: [0.00, 0.20],
  },
  {
    id: 'agencia-valenciana-antifrau',
    nom: 'Agència Valenciana Antifrau',
    tipus: 'legal',
    ambit: 'Corrupció i fons públics (PV)',
    descripcio_breu: 'Investiga corrupció i irregularitats a les administracions del País Valencià.',
    per_a_que: 'Denunciar corrupció o ús indegut de recursos públics al País Valencià.',
    quan_usar: [
      'Contractes públics sospitosos al PV',
      'Nepotisme o tracte de favor',
      'Ús irregular de diners públics',
    ],
    que_esperar: [
      'Investigació confidencial',
      'Possible trasllat a fiscalia',
    ],
    punts_forts: ['Canal de denúncia protegit', 'Independència'],
    limitacions: ['Àmbit només PV'],
    resultat_habitual: 'Investigació i, si escau, accions legals.',
    temps: 'Mesos',
    enllac: 'https://www.antifraucv.es/va/bustia-de-denuncies-2/',
    pos:       [0.733, 0.75],
    pos_mobil: [0.67, 0.90],
  },
  {
    id: 'escola-valenciana',
    nom: 'Escola Valenciana',
    tipus: 'social',
    ambit: 'Ensenyament en valencià (PV)',
    descripcio_breu: 'Federació d\'entitats que defensa l\'ensenyament i els drets lingüístics en valencià.',
    per_a_que: 'Sumar-te o denunciar incompliments a l\'ensenyament en valencià i drets lingüístics al PV.',
    quan_usar: [
      'Problemes amb ensenyament en valencià',
      'Vulneracions de drets lingüístics al PV',
      'Defensa de la llengua al sistema educatiu',
    ],
    que_esperar: [
      'Incidència política',
      'Campanyes i mobilitzacions',
    ],
    punts_forts: ['Referent educatiu al PV', 'Base social àmplia'],
    limitacions: ['No és un canal de queixa individual formal'],
    resultat_habitual: 'Pressió política i visibilitat.',
    temps: 'Variable',
    enllac: 'https://escolavalenciana.org/contacte-valencia/',
    pos:       [0.267, 0.125],
    pos_mobil: [0.33, 0.00],
  },
  {
    id: 'accio-ecologista-agro',
    nom: 'Acció Ecologista-Agró',
    tipus: 'sectorial',
    ambit: 'Medi ambient (País Valencià)',
    descripcio_breu: 'Entitat ecologista de referència al País Valencià, amb capacitat jurídica i territorial.',
    per_a_que: 'Denunciar impactes ambientals al País Valencià amb suport tècnic i jurídic.',
    quan_usar: [
      'Contaminació o impactes ambientals al PV',
      'Projectes destructius al territori',
      'Afectacions a espais naturals valencians',
    ],
    que_esperar: [
      'Acompanyament tècnic',
      'Possibles accions legals',
      'Difusió pública',
    ],
    punts_forts: ['Arrelament territorial', 'Trajectòria'],
    limitacions: ['Focus País Valencià'],
    resultat_habitual: 'Bloqueig o modificació de projectes, denúncia pública.',
    temps: 'Mesos / anys',
    enllac: 'https://accioecologista-agro.org/contacte/',
    pos:       [0.60, 0.25],
    pos_mobil: [0.83, 0.20],
  },

  // ══════════════════════════════════════════
  //  CATALUNYA NORD
  // ══════════════════════════════════════════
  {
    id: 'aplec',
    nom: 'APLEC — Catalunya Nord',
    tipus: 'social',
    ambit: 'Ensenyament del català (Catalunya Nord)',
    descripcio_breu: 'Associació per l\'ensenyament del català a la Catalunya Nord.',
    per_a_que: 'Donar suport i denunciar dificultats en l\'ensenyament del català a la Catalunya Nord.',
    quan_usar: [
      'Problemes amb l\'ensenyament del català al nord',
      'Defensa de la llengua en àmbits educatius i socials',
    ],
    que_esperar: [
      'Acompanyament',
      'Campanyes i incidència',
    ],
    punts_forts: ['Referent a la Catalunya Nord', 'Web en català'],
    limitacions: ['Àmbit geogràfic concret'],
    resultat_habitual: 'Pressió i visibilitat.',
    temps: 'Variable',
    enllac: 'https://aplec.cat/contacteu/',
    pos:       [0.533, 0.875],
    pos_mobil: [0.67, 0.20],
  },

  // ══════════════════════════════════════════
  //  ANDORRA
  // ══════════════════════════════════════════
  {
    id: 'raonador-andorra',
    nom: 'Raonador del Ciutadà d\'Andorra',
    tipus: 'administratiu',
    ambit: 'Drets davant l\'administració (Andorra)',
    descripcio_breu: 'Defensor del ciutadà davant les administracions del Principat d\'Andorra.',
    per_a_que: 'Reclamar davant les administracions andorranes quan es vulneren drets o no responen.',
    quan_usar: [
      'Silenci administratiu a Andorra',
      'Serveis públics andorrans mal gestionats',
      'Tracte injust d\'una administració andorrana',
    ],
    que_esperar: [
      'Investigació del cas',
      'Recomanacions a l\'administració',
    ],
    punts_forts: ['Independent', 'Cobertura específica d\'Andorra'],
    limitacions: ['No pot sancionar'],
    resultat_habitual: 'Revisió o rectificació administrativa.',
    temps: 'Setmanes / mesos',
    enllac: 'https://forms.cloud.microsoft/e/ahhCVauT00?lang=ca-ES',
    pos:       [0.067, 0.625],
    pos_mobil: [0.33, 0.70],
  },
  {
    id: 'ibsalut',
    nom: 'Servei de Salut de les Illes Balears (IbSalut)',
    tipus: 'administratiu',
    ambit: 'Sanitat pública (IB)',
    descripcio_breu: 'Queixes sobre CAPs, hospitals, llistes d\'espera o errors sanitaris a les Illes Balears.',
    per_a_que: 'Fer arribar una queixa sobre l\'atenció sanitària pública a les Illes.',
    quan_usar: [
      'Mala atenció al CAP o hospital a IB',
      'Llistes d\'espera excessives',
      'Errors sanitaris o de gestió',
      'Problemes amb targeta sanitària IB',
    ],
    que_esperar: [
      'Resposta del centre o gerència',
      'Revisió del cas',
    ],
    punts_forts: ['Via oficial', 'Obligació de resposta'],
    limitacions: ['Ritme administratiu', 'No indemnitza directament'],
    resultat_habitual: 'Resposta del centre amb explicació o mesures correctores.',
    temps: 'Setmanes',
    enllac: 'https://qssi.ibsalut.es/qssifront/index.xhtml',
    pos:       [0.80, 0.375],
    pos_mobil: [0.17, 0.10],
  },
  {
    id: 'ibavi',
    nom: 'Institut Balear de l\'Habitatge (IBAVI)',
    tipus: 'administratiu',
    ambit: 'Habitatge públic (IB)',
    descripcio_breu: 'Queixes i consultes sobre habitatge públic, ajudes i drets a les Illes Balears.',
    per_a_que: 'Fer arribar queixes o consultes sobre polítiques d\'habitatge del Govern Balear.',
    quan_usar: [
      'Problemes amb habitatge de protecció oficial',
      'Ajudes al lloguer a IB',
      'Drets d\'habitatge',
    ],
    que_esperar: [
      'Resposta administrativa de l\'IBAVI',
      'Derivació al servei competent',
    ],
    punts_forts: ['Canal oficial específic', 'Obligació de resposta'],
    limitacions: ['Només temes d\'habitatge IB'],
    resultat_habitual: 'Resposta formal o derivació.',
    temps: 'Setmanes',
    enllac: 'https://www.caib.es/sites/habitatges/ca/fcontacto/queixes_suggeriments_agraiments/',
    pos:       [0.333, 0.00],
    pos_mobil: [0.50, 0.00],
  },
  {
    id: 'ibdona',
    nom: 'Institut Balear de la Dona (IBDONA)',
    tipus: 'administratiu',
    ambit: 'Violència masclista (canal oficial IB)',
    descripcio_breu: 'Organisme del Govern Balear per a l\'atenció a dones víctimes de violència masclista a les Illes.',
    per_a_que: 'Rebre atenció, recursos i acompanyament de l\'administració pública balear en casos de violència masclista.',
    quan_usar: [
      'Violència masclista a la parella o exparella (IB)',
      'Assetjament sexual o laboral per raó de gènere',
      'Necessites recursos d\'acollida o suport a les Illes',
    ],
    que_esperar: [
      'Atenció especialitzada',
      'Derivació a recursos (acollida, jurídic, psicològic)',
    ],
    punts_forts: ['Canal oficial', 'Xarxa de recursos pública'],
    limitacions: ['Específicament dones víctimes de violència masclista', 'Àmbit només IB'],
    resultat_habitual: 'Atenció i activació de recursos segons el cas.',
    temps: 'Dies / setmanes',
    enllac: 'https://www.caib.es/webgoib/vols-informaci%C3%B3-o-ajuda-sobre-la-viol%C3%A8ncia-contra-les-dones-',
    pos:       [0.55, 0.05],
    pos_mobil: [0.67, 0.05],
  },
  {
    id: 'drets-linguistics-ib',
    nom: 'Oficina de Defensa dels Drets Lingüístics (IB)',
    tipus: 'administratiu',
    ambit: 'Drets lingüístics (IB, canal oficial)',
    descripcio_breu: 'Organisme del Govern Balear per a denúncies sobre drets del català a les Illes.',
    per_a_que: 'Fer arribar al Govern Balear una queixa oficial en matèria de català.',
    quan_usar: [
      'Administracions o serveis que no respecten el català a IB',
      'Incompliments normatius en matèria lingüística',
      'Discriminació per parlar català',
    ],
    que_esperar: [
      'Investigació i resposta oficial',
      'Derivació a l\'òrgan competent',
    ],
    punts_forts: ['Canal oficial específic', 'Obligació de resposta'],
    limitacions: ['Competència només a les Illes'],
    resultat_habitual: 'Resposta o mesures correctores segons el cas.',
    temps: 'Setmanes',
    enllac: 'https://www.caib.es/seucaib/ca/200/persones/tramites/tramite/4454533',
    pos:       [0.40, 0.75],
    pos_mobil: [0.00, 0.40],
  },
  {
    id: 'consum-ib',
    nom: 'Consum — Illes Balears',
    tipus: 'administratiu',
    ambit: 'Consumidors i empreses (IB)',
    descripcio_breu: 'Reclamacions, denúncies i consultes de consum a les Illes Balears.',
    per_a_que: 'Reclamar davant empreses per serveis o productes defectuosos a les Illes.',
    quan_usar: [
      'Cobraments indeguts a IB',
      'Contractes enganyosos',
      'Serveis defectuosos (telecos, llum, aigua, bancs...)',
    ],
    que_esperar: [
      'Mediació amb l\'empresa',
      'Possible sanció administrativa',
    ],
    punts_forts: ['Molts casos es resolen', 'Via oficial reconeguda'],
    limitacions: ['Cal haver reclamat abans a l\'empresa', 'Lent'],
    resultat_habitual: 'Acord amb l\'empresa o resolució administrativa.',
    temps: 'Setmanes / mesos',
    enllac: 'https://www.caib.es/sites/consumidor/ca/reclamacions_denuncies_i_consultes-90/',
    pos:       [0.60, 0.50],
    pos_mobil: [0.17, 0.90],
  },
  {
    id: 'tib-transports-ib',
    nom: 'Transports de les Illes Balears (TIB)',
    tipus: 'administratiu',
    ambit: 'Transport públic (IB)',
    descripcio_breu: 'Reclamacions i suggeriments sobre el transport públic de les Illes Balears.',
    per_a_que: 'Fer arribar una queixa o suggeriment al consorci de transports balear (TIB).',
    quan_usar: [
      'Incidències amb bus, metro, ferrocarril IB',
      'Horaris, puntualitat, atenció',
      'Accessibilitat al transport públic',
    ],
    que_esperar: [
      'Resposta del consorci',
      'Possible rectificació del servei',
    ],
    punts_forts: ['Canal específic del servei', 'Obligació de resposta'],
    limitacions: ['Només transport IB'],
    resultat_habitual: 'Resposta o mesura correctora.',
    temps: 'Dies / setmanes',
    enllac: 'https://www.tib.org/web/ctm/reclamacions-i-suggeriments',
    pos:       [0.133, 0.25],
    pos_mobil: [0.00, 0.70],
  },
  {
    id: 'accessibilitat-ib',
    nom: 'Accessibilitat de webs i apps (IB)',
    tipus: 'administratiu',
    ambit: 'Accessibilitat digital (IB)',
    descripcio_breu: 'Queixes per incompliment de requisits d\'accessibilitat en webs i apps públiques de les Illes.',
    per_a_que: 'Denunciar que una web o app pública del Govern Balear no és accessible per a persones amb discapacitat.',
    quan_usar: [
      'Webs/apps del Govern Balear no accessibles',
      'Documents no accessibles amb lector de pantalla',
      'Problemes d\'accessibilitat digital en serveis públics IB',
    ],
    que_esperar: [
      'Resposta de l\'òrgan responsable',
      'Possibles correccions tècniques',
    ],
    punts_forts: ['Canal oficial per accessibilitat', 'Regulat per normativa europea'],
    limitacions: ['Només webs/apps públiques IB'],
    resultat_habitual: 'Adaptació o justificació del responsable.',
    temps: 'Setmanes',
    enllac: 'https://www.caib.es/seucaib/ca/200/persones%20/tramites/servicio/3665443',
    pos:       [0.267, 0.50],
    pos_mobil: [0.83, 0.90],
  },
];

// ─── Assignació de territori per a cada entitat ────────
const _TERRITORI_BY_ID = {
  // Catalunya (Principat)
  'sindic-greuges':         'cat',
  'consum':                 'cat',
  'catsalut':               'cat',
  'generalitat-instancia':  'cat',
  'politica-linguistica':   'cat',
  'oac-ajuntaments':        'cat',
  'antifrau':               'cat',
  'mossos':                 'cat',
  'apdcat':                 'cat',
  'jutjat-guardia':         'cat',
  'iridia':                 'cat',
  'omnium':                 'cat',
  'facua':                  'cat',
  'observatori-desc':       'cat',
  'intersindical':          'cat',
  'adenc':                  'cat',
  'sindicat-llogateres':    'cat',
  'entrebarris':            'cat',
  'institut-catala-dones':  'cat',
  'helia':                  'cat',
  'fundacio-surt':          'cat',
  'observatori-homofobia':  'cat',
  'casal-lambda':           'cat',
  'fundacio-enllac':        'cat',
  'acathi':                 'cat',
  'lambda-valencia':        'val',
  'depana':                 'cat',
  'iaeden':                 'cat',
  'plataforma-ebre':        'cat',
  'sos-costa-brava':        'cat',
  'no-a-la-mat':            'cat',
  'xuquer-viu':             'val',
  'per-l-horta':            'val',
  'amics-terra':            'bal',
  'terraferida':            'bal',
  'salvem-sa-badia':        'bal',
  'contenidor-rac1':        'cat',
  'sos-racisme':            'cat',
  'justicia-i-pau':         'cat',
  'gepec':                  'cat',

  // Illes Balears
  'sindic-ib':              'bal',
  'ocb':                    'bal',
  'gob':                    'bal',
  'ibsalut':                'bal',
  'ibavi':                  'bal',
  'ibdona':                 'bal',
  'drets-linguistics-ib':   'bal',
  'consum-ib':              'bal',
  'tib-transports-ib':      'bal',
  'accessibilitat-ib':      'bal',

  // País Valencià
  'acpv':                   'val',
  'sindic-cv':              'val',
  'agencia-valenciana-antifrau': 'val',
  'escola-valenciana':      'val',
  'accio-ecologista-agro':  'val',

  // Catalunya Nord
  'aplec':                  'cn',

  // Afegits posteriors

  // Andorra
  'raonador-andorra':       'and',

  // Transversals (Països Catalans)
  'plataforma-llengua':     'paisos',
  'accio-cassandra':        'paisos',
  'accio-pel-catala':       'paisos',
};
ENTITATS.forEach(e => { e.territori = _TERRITORI_BY_ID[e.id] || 'cat'; });

// ─── Adreces i telèfons ───────────────────────────────
// Ús: si adreca o telefon estan buits ('—' o ''), la UI no els mostrarà.
const _CONTACTE_BY_ID = {
  'sindic-greuges':         { adreca: 'Passeig de Lluís Companys, 7, 08003 Barcelona', telefon: '900 124 124' },
  'consum':                 { adreca: 'Carrer del Foc, 57, 08038 Barcelona',             telefon: '93 857 40 00' },
  'catsalut':               { adreca: 'Travessera de les Corts, 131-159, Edifici Olímpia, 08028 Barcelona', telefon: '93 403 85 85' },
  'generalitat-instancia':  { adreca: '',                                                 telefon: '012' },
  'politica-linguistica':   { adreca: '',                                                 telefon: '012' },
  'oac-ajuntaments':        { adreca: '',                                                 telefon: '012' },
  'antifrau':               { adreca: 'Carrer de Ribes, 1-3, 08013 Barcelona',            telefon: '93 554 55 55' },
  'mossos':                 { adreca: '',                                                 telefon: '112 (emergències)' },
  'apdcat':                 { adreca: 'Gran Via de les Corts Catalanes, 635, 08010 Barcelona', telefon: '93 552 78 00' },
  'jutjat-guardia':         { adreca: '',                                                 telefon: '900 12 18 84 (víctimes)' },
  'accio-cassandra':        { adreca: '',                                                 telefon: '' },
  'iridia':                 { adreca: 'Riera d\'Escuder, 38 Nau 1 baixos, 08028 Barcelona', telefon: '693 287 323' },
  'plataforma-llengua':     { adreca: 'Carrer de Sant Honorat, 7 Principal 1a, 08002 Barcelona', telefon: '93 321 18 03' },
  'omnium':                 { adreca: 'Carrer de la Diputació, 276, pral., 08009 Barcelona', telefon: '93 319 80 50' },
  'facua':                  { adreca: 'Carrer de Leiva, 25, 08014 Barcelona',              telefon: '688 954 954' },
  'observatori-desc':       { adreca: 'Carrer de Casp, 43, baixos, 08010 Barcelona',       telefon: '93 302 68 82' },
  'intersindical':          { adreca: 'Carrer de Rocafort, 242 bis, 08029 Barcelona',      telefon: '93 481 36 60' },
  'adenc':                  { adreca: '',                                                 telefon: '' },
  'sindicat-llogateres':    { adreca: '',                                                 telefon: '' },
  'entrebarris':            { adreca: '',                                                 telefon: '' },
  'institut-catala-dones':  { adreca: '',                                                 telefon: '900 900 120 (24h, gratuït)' },
  'helia':                  { adreca: '',                                                 telefon: '' },
  'fundacio-surt':          { adreca: '',                                                 telefon: '' },
  'observatori-homofobia':  { adreca: '',                                                 telefon: '' },
  'casal-lambda':           { adreca: '',                                                 telefon: '' },
  'fundacio-enllac':        { adreca: '',                                                 telefon: '' },
  'acathi':                 { adreca: '',                                                 telefon: '' },
  'lambda-valencia':        { adreca: '',                                                 telefon: '' },
  'depana':                 { adreca: '',                                                 telefon: '' },
  'iaeden':                 { adreca: '',                                                 telefon: '' },
  'plataforma-ebre':        { adreca: '',                                                 telefon: '' },
  'sos-costa-brava':        { adreca: '',                                                 telefon: '' },
  'no-a-la-mat':            { adreca: '',                                                 telefon: '' },
  'xuquer-viu':             { adreca: '',                                                 telefon: '' },
  'per-l-horta':            { adreca: '',                                                 telefon: '' },
  'amics-terra':            { adreca: '',                                                 telefon: '' },
  'terraferida':            { adreca: '',                                                 telefon: '' },
  'salvem-sa-badia':        { adreca: '',                                                 telefon: '' },
  'contenidor-rac1':        { adreca: '',                                                 telefon: '669 10 10 10 (WhatsApp)' },
  'sos-racisme':            { adreca: 'Carrer de Maria Casas Mira, 38, 08001 Barcelona',   telefon: '652 87 34 06' },
  'justicia-i-pau':         { adreca: 'Carrer de Roger de Llúria, 126, 3r 1a, 08037 Barcelona', telefon: '622 561 495' },
  'acpv':                   { adreca: 'Carrer de Sant Ferran, 12, 46001 València',         telefon: '96 315 77 99' },
  'gepec':                  { adreca: '',                                                 telefon: '977 33 11 42' },
  'accio-pel-catala':       { adreca: '',                                                 telefon: '' },
  'sindic-ib':              { adreca: '',                                                 telefon: '012' },
  'ocb':                    { adreca: 'Carrer de Sant Alonso, 24, 07001 Palma',            telefon: '971 72 32 99' },
  'gob':                    { adreca: 'Carrer de Manuel Sanchis Guarner, 10, 07004 Palma', telefon: '971 49 60 60' },
  'sindic-cv':              { adreca: 'Carrer Pascual Blasco, 1, 03001 Alacant',           telefon: '900 210 970' },
  'agencia-valenciana-antifrau': { adreca: 'Carrer Navellos, 14, porta 3, 46003 València', telefon: '96 278 74 50' },
  'escola-valenciana':      { adreca: 'Carrer d\'Antoni Maura, 18 baix, 12001 Castelló de la Plana', telefon: '659 04 13 95' },
  'accio-ecologista-agro':  { adreca: 'Portal de Valldigna, 15, 46003 València',           telefon: '96 391 78 64' },
  'aplec':                  { adreca: 'Universitat de Perpinyà, P1, Casa dels Països Catalans, Camí de la Passió Vella, 66860 Perpinyà Cedex', telefon: '+33 4 68 66 22 11' },
  'raonador-andorra':       { adreca: '',                                                 telefon: '+376 180 030 30' },
  'ibsalut':                { adreca: '',                                                 telefon: '971 17 56 00' },
  'ibavi':                  { adreca: '',                                                 telefon: '971 78 49 90' },
  'ibdona':                 { adreca: '',                                                 telefon: '' },
  'drets-linguistics-ib':   { adreca: '',                                                 telefon: '012' },
  'consum-ib':              { adreca: '',                                                 telefon: '971 17 65 58' },
  'tib-transports-ib':      { adreca: '',                                                 telefon: '971 17 77 77' },
  'accessibilitat-ib':      { adreca: '',                                                 telefon: '012' },
};
ENTITATS.forEach(e => {
  const c = _CONTACTE_BY_ID[e.id] || {};
  e.adreca = c.adreca || '';
  e.telefon = c.telefon || '';
  e.email = c.email || '';
});

// ─── Emails de contacte (només els que hem pogut verificar) ───────────
const _EMAIL_BY_ID = {
  // Confirmats via web o proporcionats per l'usuari
  'accio-cassandra':    'acciocassandra@proton.me',
  'contenidor-rac1':    'elmon@rac1.net',
  'intersindical':      'contacte@laintersindical.cat',
  'justicia-i-pau':     'justiciaipau@justiciaipau.org',
  'antifrau':           'bustiaoac@antifrau.cat',
  // Estàndards molt coneguts (domini oficial de la pròpia entitat)
  'sindic-greuges':     'sindic@sindic.cat',
  'omnium':             'info@omnium.cat',
  'apdcat':             'apdcat@gencat.cat',
  'plataforma-llengua': 'info@plataforma-llengua.cat',
  'observatori-desc':   'observatori@observatoridesca.org',
  'facua':              'consultas@facua.org',
  'sos-racisme':        'federacio@sosracisme.org',
  'acpv':               'acpv@acpv.cat',
  'ocb':                'ocb@ocb.cat',
  'gob':                'info@gobmallorca.com',
  'gepec':              'secretaria@gepec.cat',
  'catsalut':           'atenciociutadania@catsalut.cat',
  'observatori-homofobia': 'denuncia@lobservatori.cat',
  'casal-lambda':       'assessoriajuridica@lambda.cat',
  'fundacio-enllac':    'enllac@fundacioenllac.cat',
  // Batch abril 2026
  'iridia':                      'info@iridia.cat',
  'adenc':                       'correu@adenc.cat',
  'sindicat-llogateres':         'sindicat@sindicatdellogateres.org',
  'entrebarris':                 'info@entrebarris.org',
  'institut-catala-dones':       'icd@gencat.cat',
  'helia':                       'helia@heliadones.org',
  'fundacio-surt':               'surt@surt.org',
  'acathi':                      'acathi@acathi.org',
  'lambda-valencia':             'info@lambdavalencia.org',
  'depana':                      'info@depana.org',
  'iaeden':                      'iaeden@iaeden.cat',
  'plataforma-ebre':             'plataformadefensaebre@gmail.com',
  'sos-costa-brava':             'hola@soscostabrava.cat',
  'no-a-la-mat':                 'noalamatselva@gmail.com',
  'xuquer-viu':                  'coordinadora@xuquerviu.net',
  'per-l-horta':                 'perlhorta@perlhorta.info',
  'salvem-sa-badia':             'salvemsabadiadeportmany@gmail.com',
  'sindic-cv':                   'consultes@elsindic.com',
  'agencia-valenciana-antifrau': 'comunicacion@antifraucv.es',
  'accio-ecologista-agro':       'lhorta@accioecologista-agro.org',
  'aplec':                       'aplec@aplec.cat',
  'drets-linguistics-ib':        'oficina@ieb.caib.es',
  'ibavi':                       'altresconsultes.mca@ibavi.caib.es',
  'ibdona':                      'ibdona@ibdona.caib.es',
  'consum-ib':                   'secretaria@dgconsum.caib.es',
};
ENTITATS.forEach(e => {
  if (!e.email && _EMAIL_BY_ID[e.id]) e.email = _EMAIL_BY_ID[e.id];
});

// ─── Abast "Més enllà dels PPCC" ───
// Entitats que poden ajudar persones que estan fora dels Països Catalans
// (diàspora, residents a l'estranger, consumidors UE, etc.).
const _MESENLLA_IDS = new Set([
  'justicia-i-pau',      // xarxa internacional de drets humans i pau
  'facua',               // via BEUC cobreix consumidors a tota la UE
  'plataforma-llengua',  // atenció a la diàspora en temes lingüístics
  'omnium',              // vincle amb la diàspora catalana
]);
ENTITATS.forEach(e => { if (_MESENLLA_IDS.has(e.id)) e.mesenlla = true; });

// ─── Sigles per mostrar a les icones (prioritza les oficials quan existeixen) ───
const _SIGLES_BY_ID = {
  // Catalunya
  'sindic-greuges':         'Síndic\nCat',
  'consum':                 'Consum\nCat',
  'catsalut':               'Cat\nSalut',
  'generalitat-instancia':  'Gene\nCat',
  'antifrau':               'Antifrau\nCat',
  'mossos':                 'Mossos',
  'apdcat':                 'Cat\nDades',
  'jutjat-guardia':         'Jutjats\nCat',
  'accio-cassandra':        'Acció\nCassan',
  'iridia':                 'Irídia\nDrets',
  'plataforma-llengua':     'P x\nLlengua',
  'omnium':                 'Òmnium\nCultural',
  'facua':                  'FACUA\nCat',
  'observatori-desc':       'Obs\nDESC',
  'contenidor-rac1':        'Contenidor\nRAC1',
  'sos-racisme':            'SOS\nRacisme',
  'justicia-i-pau':         'Justícia\nPau',
  'gepec':                  'GEPEC\nEdC',
  'politica-linguistica':   'Política\nLingüís',
  'accio-pel-catala':       'Acció\nCatalà',
  'intersindical':          'Inter\nsindical',
  'adenc':                  'ADENC\nNatura',
  'sindicat-llogateres':    'Sindicat Llogater',
  'entrebarris':            'Entre\nBarris',
  'institut-catala-dones':  'IC Dones',
  'helia':                  'Assoc\nHèlia',
  'fundacio-surt':          'Fundació\nSurt',
  'observatori-homofobia':  'Contra\nHomofòb',
  'casal-lambda':           'Casal\nLambda',
  'fundacio-enllac':        'Fundació\nEnllaç',
  'acathi':                 'ACATHI',
  'depana':                 'DEPANA',
  'iaeden':                 'IAEDEN',
  'plataforma-ebre':        'Defensa\nEbre',
  'sos-costa-brava':        'SOS\nCosta',
  'no-a-la-mat':            'No MAT',
  'xuquer-viu':             'Xúquer\nViu',
  'per-l-horta':            "l'Horta",
  'amics-terra':            'Terra\nMallorca',
  'terraferida':            'Terra\nFerida',
  'salvem-sa-badia':        'Salvem\nPortmany',
  'oac-ajuntaments':        'OAC',

  // País Valencià
  'acpv':                   'Acció\nCPV',
  'sindic-cv':              'Síndic\nValència',
  'agencia-valenciana-antifrau': 'AV\nAntifrau',
  'escola-valenciana':      'Escola\nValencià',
  'accio-ecologista-agro':  'Acció\nE-Agro',

  // Balears
  'sindic-ib':              'Atenció\nBalears',
  'ocb':                    'OCB\nBalear',
  'gob':                    'GOB',
  'ibsalut':                'IbSalut',
  'ibavi':                  'IBAVI',
  'ibdona':                 'IbDona',
  'drets-linguistics-ib':   'ODD\nLingüís',
  'consum-ib':              'Consum\nBalears',
  'tib-transports-ib':      'TIB',
  'accessibilitat-ib':      'Accés\nwebs',

  // Catalunya Nord
  'aplec':                  'APLEC\nCatNord',

  // Andorra
  'raonador-andorra':       'Raonador\nAndorra',
};
// ─── PROVA: sigles auto-generades amb regla uniforme ─────────
// Regla:
//   · Nom d'una sola paraula i ≤ 6 lletres → nom sencer
//   · Nom compost → inicials de totes les paraules significatives (filtra articles,
//     preposicions) limitades a 6 caràcters
// _SIGLES_BY_ID segueix com a "override" manual si calgués excepcions.
const _STOP_WORDS = new Set([
  'de','del','dels','la','el','els','les','i','a','al','als','en','per','amb',
  'd','l','contra','sobre','sense','sota'
]);
function autoSigla(nom) {
  const MAX_LINE = 8;
  // Treu parèntesis i subtítols després d'un em/en-dash
  const base = nom.replace(/\([^)]*\)/g, '').split(/\s[—–]\s|\s-\s/)[0].trim();
  const raw = base.split(/\s+/).map(w => w.replace(/[.,]$/, ''));
  const words = raw.filter(w => w && !_STOP_WORDS.has(w.toLowerCase().replace(/['']/g, '')));
  if (words.length === 0) return nom.charAt(0).toUpperCase();

  // Regla 1: nom curt d'una línia (inclou els acrònims ja d'1 paraula llarga)
  const joined = words.join(' ');
  if (joined.length <= MAX_LINE) return joined;

  // Regla 2: múltiples paraules → 2 línies balancejades al punt de tall més equilibrat
  if (words.length >= 2) {
    let best = null;
    for (let i = 1; i < words.length; i++) {
      const l1 = words.slice(0, i).join(' ');
      const l2 = words.slice(i).join(' ');
      if (l1.length > MAX_LINE || l2.length > MAX_LINE) continue;
      const diff = Math.abs(l1.length - l2.length);
      if (!best || diff < best.diff) best = { text: l1 + '\n' + l2, diff };
    }
    if (best) return best.text;
    // Cap combinació encaixa en 2 línies → inicials
    return words.map(w => w.charAt(0).toUpperCase()).join('').slice(0, 6);
  }

  // Regla 3: 1 paraula llarga (EntreBarris, Terraferida…) → partir pel mig
  const w = words[0];
  // Preferència: trencar abans d'una majúscula interna si n'hi ha (camelCase)
  const camel = w.slice(1).search(/[A-ZÀ-Ü]/);
  const cut = camel > 0 ? camel + 1 : Math.ceil(w.length / 2);
  return w.slice(0, cut) + '\n' + w.slice(cut);
}
// Prioritat: sigla manual de _SIGLES_BY_ID; si no n'hi ha, autoSigla.
ENTITATS.forEach(e => {
  e.sigles = _SIGLES_BY_ID[e.id] || autoSigla(e.nom) || e.nom.charAt(0).toUpperCase();
});

// ─── Temàtiques per entitat (per a la pregunta «De què es tracta?») ───
const _TEMATIQUES_BY_ID = {
  // Administració general / queixes formals
  'sindic-greuges':         ['admin'],
  'generalitat-instancia':  ['admin'],
  'oac-ajuntaments':        ['admin'],
  'sindic-ib':              ['admin'],
  'sindic-cv':              ['admin'],
  'raonador-andorra':       ['admin'],
  // Consum
  'consum':                 ['consum'],
  'consum-ib':              ['consum'],
  'facua':                  ['consum'],
  'contenidor-rac1':        ['consum', 'admin', 'qualsevol'],
  // Salut
  'catsalut':               ['salut'],
  'ibsalut':                ['salut'],
  // Corrupció
  'antifrau':               ['corrupcio'],
  'agencia-valenciana-antifrau': ['corrupcio'],
  // Delicte i via judicial
  'mossos':                 ['delicte', 'delicte_odi'],
  'jutjat-guardia':         ['delicte', 'delicte_odi'],
  // Dades
  'apdcat':                 ['dades'],
  // Llengua + catalanofòbia
  'politica-linguistica':   ['llengua'],
  'plataforma-llengua':     ['llengua', 'catalanofobia'],
  'accio-pel-catala':       ['llengua'],
  'drets-linguistics-ib':   ['llengua'],
  'ocb':                    ['llengua'],
  'acpv':                   ['llengua'],
  'escola-valenciana':      ['llengua', 'ensenyament'],
  'aplec':                  ['llengua', 'ensenyament'],
  // Drets humans / civils
  'iridia':                 ['drets_humans'],
  'justicia-i-pau':         ['drets_humans'],
  'omnium':                 ['drets_humans', 'llengua'],
  // Nació / catalanofòbia (Acció Cassandra)
  'accio-cassandra':        ['catalanofobia', 'drets_humans', 'delicte_odi'],
  // Habitatge
  'observatori-desc':       ['habitatge'],
  'ibavi':                  ['habitatge'],
  'ibdona':                 ['violencia_masclista'],
  // Medi ambient
  'gepec':                  ['medi_ambient'],
  'gob':                    ['medi_ambient'],
  'adenc':                  ['medi_ambient'],
  'sindicat-llogateres':    ['habitatge'],
  'entrebarris':            ['habitatge'],
  'institut-catala-dones':  ['violencia_masclista'],
  'helia':                  ['violencia_masclista'],
  'fundacio-surt':          ['violencia_masclista'],
  'observatori-homofobia':  ['lgtbi', 'delicte_odi'],
  'casal-lambda':           ['lgtbi'],
  'fundacio-enllac':        ['lgtbi'],
  'acathi':                 ['lgtbi', 'racisme'],
  'lambda-valencia':        ['lgtbi'],
  'depana':                 ['medi_ambient'],
  'iaeden':                 ['medi_ambient'],
  'plataforma-ebre':        ['medi_ambient'],
  'sos-costa-brava':        ['medi_ambient'],
  'no-a-la-mat':            ['medi_ambient'],
  'xuquer-viu':             ['medi_ambient'],
  'per-l-horta':            ['medi_ambient'],
  'amics-terra':            ['medi_ambient'],
  'terraferida':            ['medi_ambient'],
  'salvem-sa-badia':        ['medi_ambient'],
  'accio-ecologista-agro':  ['medi_ambient'],
  // Laboral
  'intersindical':          ['laboral'],
  // Transport
  'tib-transports-ib':      ['transport'],
  // Accessibilitat digital
  'accessibilitat-ib':      ['accessibilitat'],
  // Racisme
  'sos-racisme':            ['racisme', 'catalanofobia', 'delicte_odi'],
};
ENTITATS.forEach(e => { e.tematiques = _TEMATIQUES_BY_ID[e.id] || []; });
